package cpu

type InstructionInfo struct {
	Mnemonic string
	Parameters string
	DataBytes uint8
}

var DisassemblyTable_Unprefixed = map[uint8]InstructionInfo {
	0x00: InstructionInfo{"nop", "", 0},
	0x01: InstructionInfo{"ld", "bc, %d16", 2},
	0x02: InstructionInfo{"ld", "[bc], a", 0},
	0x03: InstructionInfo{"inc", "bc", 0},
	0x04: InstructionInfo{"inc", "b", 0},
	0x05: InstructionInfo{"dec", "b", 0},
	0x06: InstructionInfo{"ld", "b, %d8", 1},
	0x07: InstructionInfo{"rlca", "", 0},
	0x08: InstructionInfo{"ex", "af, af'", 0},
	0x09: InstructionInfo{"add", "hl, bc", 0},
	0x0A: InstructionInfo{"ld", "a, [bc]", 0},
	0x0B: InstructionInfo{"dec", "bc", 0},
	0x0C: InstructionInfo{"inc", "c", 0},
	0x0D: InstructionInfo{"dec", "c", 0},
	0x0E: InstructionInfo{"ld", "c, %d8", 1},
	0x0F: InstructionInfo{"rrca", "", 0},
	0x10: InstructionInfo{"djnz", "%d16", 2},
	0x11: InstructionInfo{"ld", "de, %d16", 2},
	0x12: InstructionInfo{"ld", "[de], a", 0},
	0x13: InstructionInfo{"inc", "de", 0},
	0x14: InstructionInfo{"inc", "d", 0},
	0x15: InstructionInfo{"dec", "d", 0},
	0x16: InstructionInfo{"ld", "d, %d8", 1},
	0x17: InstructionInfo{"rla", "", 0},
	0x18: InstructionInfo{"jr", "%d16", 2},
	0x19: InstructionInfo{"add", "hl, de", 0},
	0x1A: InstructionInfo{"ld", "a, [de]", 0},
	0x1B: InstructionInfo{"dec", "de", 0},
	0x1C: InstructionInfo{"inc", "e", 0},
	0x1D: InstructionInfo{"dec", "e", 0},
	0x1E: InstructionInfo{"ld", "e, %d8", 1},
	0x1F: InstructionInfo{"rra", "", 0},
	0x20: InstructionInfo{"jr", "nz, %d16", 2},
	0x21: InstructionInfo{"ld", "hl, %d16", 2},
	0x22: InstructionInfo{"ld", "[%d16], h", 2},
	0x23: InstructionInfo{"inc", "hl", 0},
	0x24: InstructionInfo{"inc", "h", 0},
	0x25: InstructionInfo{"dec", "h", 0},
	0x26: InstructionInfo{"ld", "h, %d8", 1},
	0x27: InstructionInfo{"daa", "", 0},
	0x28: InstructionInfo{"jr", "z, %d16", 2},
	0x29: InstructionInfo{"add", "hl, hl", 0},
	0x2A: InstructionInfo{"ld", "hl, [%d16]", 2},
	0x2B: InstructionInfo{"dec", "hl", 0},
	0x2C: InstructionInfo{"inc", "l", 0},
	0x2D: InstructionInfo{"dec", "l", 0},
	0x2E: InstructionInfo{"ld", "l, %d8", 1},
	0x2F: InstructionInfo{"cpl", "", 0},
	0x30: InstructionInfo{"jr", "nc, %d16", 2},
	0x31: InstructionInfo{"ld", "sp, %d16", 2},
	0x32: InstructionInfo{"ld", "[%d16], a", 2},
	0x33: InstructionInfo{"inc", "sp", 0},
	0x34: InstructionInfo{"inc", "[hl]", 0},
	0x35: InstructionInfo{"dec", "[hl]", 0},
	0x36: InstructionInfo{"ld", "[hl], %d8", 1},
	0x37: InstructionInfo{"scf", "", 0},
	0x38: InstructionInfo{"jr", "c, %d16", 2},
	0x39: InstructionInfo{"add", "hl, sp", 0},
	0x3A: InstructionInfo{"ld", "a, [%d16]", 2},
	0x3B: InstructionInfo{"dec", "sp", 0},
	0x3C: InstructionInfo{"inc", "a", 0},
	0x3D: InstructionInfo{"dec", "a", 0},
	0x3E: InstructionInfo{"ld", "a, %d8", 1},
	0x3F: InstructionInfo{"ccf", "", 0},
	0x40: InstructionInfo{"ld", "b, b", 0},
	0x41: InstructionInfo{"ld", "b, c", 0},
	0x42: InstructionInfo{"ld", "b, d", 0},
	0x43: InstructionInfo{"ld", "b, e", 0},
	0x44: InstructionInfo{"ld", "b, h", 0},
	0x45: InstructionInfo{"ld", "b, l", 0},
	0x46: InstructionInfo{"ld", "b, [hl]", 0},
	0x47: InstructionInfo{"ld", "b, a", 0},
	0x48: InstructionInfo{"ld", "c, b", 0},
	0x49: InstructionInfo{"ld", "c, c", 0},
	0x4A: InstructionInfo{"ld", "c, d", 0},
	0x4B: InstructionInfo{"ld", "c, e", 0},
	0x4C: InstructionInfo{"ld", "c, h", 0},
	0x4D: InstructionInfo{"ld", "c, l", 0},
	0x4E: InstructionInfo{"ld", "c, [hl]", 0},
	0x4F: InstructionInfo{"ld", "c, a", 0},
	0x50: InstructionInfo{"ld", "d, b", 0},
	0x51: InstructionInfo{"ld", "d, c", 0},
	0x52: InstructionInfo{"ld", "d, d", 0},
	0x53: InstructionInfo{"ld", "d, e", 0},
	0x54: InstructionInfo{"ld", "d, h", 0},
	0x55: InstructionInfo{"ld", "d, l", 0},
	0x56: InstructionInfo{"ld", "d, [hl]", 0},
	0x57: InstructionInfo{"ld", "d, a", 0},
	0x58: InstructionInfo{"ld", "e, b", 0},
	0x59: InstructionInfo{"ld", "e, c", 0},
	0x5A: InstructionInfo{"ld", "e, d", 0},
	0x5B: InstructionInfo{"ld", "e, e", 0},
	0x5C: InstructionInfo{"ld", "e, h", 0},
	0x5D: InstructionInfo{"ld", "e, l", 0},
	0x5E: InstructionInfo{"ld", "e, [hl]", 0},
	0x5F: InstructionInfo{"ld", "e, a", 0},
	0x60: InstructionInfo{"ld", "h, b", 0},
	0x61: InstructionInfo{"ld", "h, c", 0},
	0x62: InstructionInfo{"ld", "h, d", 0},
	0x63: InstructionInfo{"ld", "h, e", 0},
	0x64: InstructionInfo{"ld", "h, h", 0},
	0x65: InstructionInfo{"ld", "h, l", 0},
	0x66: InstructionInfo{"ld", "h, [hl]", 0},
	0x67: InstructionInfo{"ld", "h, a", 0},
	0x68: InstructionInfo{"ld", "l, b", 0},
	0x69: InstructionInfo{"ld", "l, c", 0},
	0x6A: InstructionInfo{"ld", "l, d", 0},
	0x6B: InstructionInfo{"ld", "l, e", 0},
	0x6C: InstructionInfo{"ld", "l, h", 0},
	0x6D: InstructionInfo{"ld", "l, l", 0},
	0x6E: InstructionInfo{"ld", "l, [hl]", 0},
	0x6F: InstructionInfo{"ld", "l, a", 0},
	0x70: InstructionInfo{"ld", "[hl], b", 0},
	0x71: InstructionInfo{"ld", "[hl], c", 0},
	0x72: InstructionInfo{"ld", "[hl], d", 0},
	0x73: InstructionInfo{"ld", "[hl], e", 0},
	0x74: InstructionInfo{"ld", "[hl], h", 0},
	0x75: InstructionInfo{"ld", "[hl], l", 0},
	0x76: InstructionInfo{"halt", "", 0},
	0x77: InstructionInfo{"ld", "[hl], a", 0},
	0x78: InstructionInfo{"ld", "a, b", 0},
	0x79: InstructionInfo{"ld", "a, c", 0},
	0x7A: InstructionInfo{"ld", "a, d", 0},
	0x7B: InstructionInfo{"ld", "a, e", 0},
	0x7C: InstructionInfo{"ld", "a, h", 0},
	0x7D: InstructionInfo{"ld", "a, l", 0},
	0x7E: InstructionInfo{"ld", "a, [hl]", 0},
	0x7F: InstructionInfo{"ld", "a, a", 0},
	0x80: InstructionInfo{"add", "a, b", 0},
	0x81: InstructionInfo{"add", "a, c", 0},
	0x82: InstructionInfo{"add", "a, d", 0},
	0x83: InstructionInfo{"add", "a, e", 0},
	0x84: InstructionInfo{"add", "a, h", 0},
	0x85: InstructionInfo{"add", "a, l", 0},
	0x86: InstructionInfo{"add", "a, [hl]", 0},
	0x87: InstructionInfo{"add", "a, a", 0},
	0x88: InstructionInfo{"adc", "a, b", 0},
	0x89: InstructionInfo{"adc", "a, c", 0},
	0x8A: InstructionInfo{"adc", "a, d", 0},
	0x8B: InstructionInfo{"adc", "a, e", 0},
	0x8C: InstructionInfo{"adc", "a, h", 0},
	0x8D: InstructionInfo{"adc", "a, l", 0},
	0x8E: InstructionInfo{"adc", "a, [hl]", 0},
	0x8F: InstructionInfo{"adc", "a, a", 0},
	0x90: InstructionInfo{"sub", "a, b", 0},
	0x91: InstructionInfo{"sub", "a, c", 0},
	0x92: InstructionInfo{"sub", "a, d", 0},
	0x93: InstructionInfo{"sub", "a, e", 0},
	0x94: InstructionInfo{"sub", "a, h", 0},
	0x95: InstructionInfo{"sub", "a, l", 0},
	0x96: InstructionInfo{"sub", "a, [hl]", 0},
	0x97: InstructionInfo{"sub", "a, a", 0},
	0x98: InstructionInfo{"sbc", "a, b", 0},
	0x99: InstructionInfo{"sbc", "a, c", 0},
	0x9A: InstructionInfo{"sbc", "a, d", 0},
	0x9B: InstructionInfo{"sbc", "a, e", 0},
	0x9C: InstructionInfo{"sbc", "a, h", 0},
	0x9D: InstructionInfo{"sbc", "a, l", 0},
	0x9E: InstructionInfo{"sbc", "a, [hl]", 0},
	0x9F: InstructionInfo{"sbc", "a, a", 0},
	0xA0: InstructionInfo{"and", "b", 0},
	0xA1: InstructionInfo{"and", "c", 0},
	0xA2: InstructionInfo{"and", "d", 0},
	0xA3: InstructionInfo{"and", "e", 0},
	0xA4: InstructionInfo{"and", "h", 0},
	0xA5: InstructionInfo{"and", "l", 0},
	0xA6: InstructionInfo{"and", "[hl]", 0},
	0xA7: InstructionInfo{"and", "a", 0},
	0xA8: InstructionInfo{"xor", "b", 0},
	0xA9: InstructionInfo{"xor", "c", 0},
	0xAA: InstructionInfo{"xor", "d", 0},
	0xAB: InstructionInfo{"xor", "e", 0},
	0xAC: InstructionInfo{"xor", "h", 0},
	0xAD: InstructionInfo{"xor", "l", 0},
	0xAE: InstructionInfo{"xor", "[hl]", 0},
	0xAF: InstructionInfo{"xor", "a", 0},
	0xB0: InstructionInfo{"or", "b", 0},
	0xB1: InstructionInfo{"or", "c", 0},
	0xB2: InstructionInfo{"or", "d", 0},
	0xB3: InstructionInfo{"or", "e", 0},
	0xB4: InstructionInfo{"or", "h", 0},
	0xB5: InstructionInfo{"or", "l", 0},
	0xB6: InstructionInfo{"or", "[hl]", 0},
	0xB7: InstructionInfo{"or", "a", 0},
	0xB8: InstructionInfo{"cp", "b", 0},
	0xB9: InstructionInfo{"cp", "c", 0},
	0xBA: InstructionInfo{"cp", "d", 0},
	0xBB: InstructionInfo{"cp", "e", 0},
	0xBC: InstructionInfo{"cp", "h", 0},
	0xBD: InstructionInfo{"cp", "l", 0},
	0xBE: InstructionInfo{"cp", "[hl]", 0},
	0xBF: InstructionInfo{"cp", "a", 0},
	0xC0: InstructionInfo{"ret", "nz", 0},
	0xC1: InstructionInfo{"pop", "bc", 0},
	0xC2: InstructionInfo{"jp", "nz, %d16", 2},
	0xC3: InstructionInfo{"jp", "%d16", 2},
	0xC4: InstructionInfo{"call", "nz, %d16", 2},
	0xC5: InstructionInfo{"push", "bc", 0},
	0xC6: InstructionInfo{"add", "a, %d8", 1},
	0xC7: InstructionInfo{"rst", "%d8", 1},
	0xC8: InstructionInfo{"ret", "z", 0},
	0xC9: InstructionInfo{"ret", "", 0},
	0xCA: InstructionInfo{"jp", "z, %d16", 2},
	// CB prefix
	0xCC: InstructionInfo{"call", "z, %d16", 2},
	0xCD: InstructionInfo{"call", "%d16", 2},
	0xCE: InstructionInfo{"adc", "a, %d8", 1},
	0xCF: InstructionInfo{"rst", "0x08", 0},
	0xD0: InstructionInfo{"ret", "nc", 0},
	0xD1: InstructionInfo{"pop", "de", 0},
	0xD2: InstructionInfo{"jp", "nc, %d16", 2},
	0xD3: InstructionInfo{"out", "[%d8], a", 1},
	0xD4: InstructionInfo{"call", "nc, %d16", 2},
	0xD5: InstructionInfo{"push", "de", 0},
	0xD6: InstructionInfo{"sub", "a, %d8", 1},
	0xD7: InstructionInfo{"rst", "0x10", 0},
	0xD8: InstructionInfo{"ret", "c", 0},
	0xD9: InstructionInfo{"exx", "", 0},
	0xDA: InstructionInfo{"jp", "c, %d16", 2},
	0xDB: InstructionInfo{"in", "a, [%d8]", 1},
	0xDC: InstructionInfo{"call", "c, %d16", 2},
	// DD prefix
	0xDE: InstructionInfo{"sbc", "a, %d8", 1},
	0xDF: InstructionInfo{"rst", "0x18", 0},
	0xE0: InstructionInfo{"ret", "po", 0},
	0xE1: InstructionInfo{"pop", "hl", 0},
	0xE2: InstructionInfo{"jp", "po, %d16", 2},
	0xE3: InstructionInfo{"ex", "[sp], hl", 0},
	0xE4: InstructionInfo{"call", "po, %d16", 2},
	0xE5: InstructionInfo{"push", "hl", 0},
	0xE6: InstructionInfo{"and", "%d8", 1},
	0xE7: InstructionInfo{"rst", "0x20", 0},
	0xE8: InstructionInfo{"ret", "pe", 0},
	0xE9: InstructionInfo{"jp", "hl", 0},
	0xEA: InstructionInfo{"jp", "pe, %d16", 2},
	0xEB: InstructionInfo{"ex", "de, hl", 0},
	0xEC: InstructionInfo{"call", "pe, %d16", 2},
	// ED prefix
	0xEE: InstructionInfo{"xor", "%d8", 1},
	0xEF: InstructionInfo{"rst", "0x28", 0},
	0xF0: InstructionInfo{"ret", "p", 0},
	0xF1: InstructionInfo{"pop", "af", 0},
	0xF2: InstructionInfo{"jp", "p, %d16", 2},
	0xF3: InstructionInfo{"di", "", 0},
	0xF4: InstructionInfo{"call", "p, %d16", 2},
	0xF5: InstructionInfo{"push", "af", 0},
	0xF6: InstructionInfo{"or", "%d8", 1},
	0xF7: InstructionInfo{"rst", "0x30", 0},
	0xF8: InstructionInfo{"ret", "m", 0},
	0xF9: InstructionInfo{"ld", "sp, hl", 0},
	0xFA: InstructionInfo{"jp", "m, %d16", 2},
	0xFB: InstructionInfo{"ei", "", 0},
	0xFC: InstructionInfo{"call", "m, %d16", 2},
	// FD prefix
	0xFE: InstructionInfo{"cp", "%d8", 1},
	0xFF: InstructionInfo{"rst", "0x38", 0},	
}

var DisassemblyTable_CB = map[uint8]InstructionInfo {
	0x00: InstructionInfo{"rlc", "b", 0},
	0x01: InstructionInfo{"rlc", "c", 0},
	0x02: InstructionInfo{"rlc", "d", 0},
	0x03: InstructionInfo{"rlc", "e", 0},
	0x04: InstructionInfo{"rlc", "h", 0},
	0x05: InstructionInfo{"rlc", "l", 0},
	0x06: InstructionInfo{"rlc", "[hl]", 0},
	0x07: InstructionInfo{"rlc", "a", 0},
	0x08: InstructionInfo{"rrc", "b", 0},
	0x09: InstructionInfo{"rrc", "c", 0},
	0x0A: InstructionInfo{"rrc", "d", 0},
	0x0B: InstructionInfo{"rrc", "e", 0},
	0x0C: InstructionInfo{"rrc", "h", 0},
	0x0D: InstructionInfo{"rrc", "l", 0},
	0x0E: InstructionInfo{"rrc", "[hl]", 0},
	0x0F: InstructionInfo{"rrc", "a", 0},
	0x10: InstructionInfo{"rl", "b", 0},
	0x11: InstructionInfo{"rl", "c", 0},
	0x12: InstructionInfo{"rl", "d", 0},
	0x13: InstructionInfo{"rl", "e", 0},
	0x14: InstructionInfo{"rl", "h", 0},
	0x15: InstructionInfo{"rl", "l", 0},
	0x16: InstructionInfo{"rl", "[hl]", 0},
	0x17: InstructionInfo{"rl", "a", 0},
	0x18: InstructionInfo{"rr", "b", 0},
	0x19: InstructionInfo{"rr", "c", 0},
	0x1A: InstructionInfo{"rr", "d", 0},
	0x1B: InstructionInfo{"rr", "e", 0},
	0x1C: InstructionInfo{"rr", "h", 0},
	0x1D: InstructionInfo{"rr", "l", 0},
	0x1E: InstructionInfo{"rr", "[hl]", 0},
	0x1F: InstructionInfo{"rr", "a", 0},
	0x20: InstructionInfo{"sla", "b", 0},
	0x21: InstructionInfo{"sla", "c", 0},
	0x22: InstructionInfo{"sla", "d", 0},
	0x23: InstructionInfo{"sla", "e", 0},
	0x24: InstructionInfo{"sla", "h", 0},
	0x25: InstructionInfo{"sla", "l", 0},
	0x26: InstructionInfo{"sla", "[hl]", 0},
	0x27: InstructionInfo{"sla", "a", 0},
	0x28: InstructionInfo{"sra", "b", 0},
	0x29: InstructionInfo{"sra", "c", 0},
	0x2A: InstructionInfo{"sra", "d", 0},
	0x2B: InstructionInfo{"sra", "e", 0},
	0x2C: InstructionInfo{"sra", "h", 0},
	0x2D: InstructionInfo{"sra", "l", 0},
	0x2E: InstructionInfo{"sra", "[hl]", 0},
	0x2F: InstructionInfo{"sra", "a", 0},
	0x30: InstructionInfo{"sls", "b", 0},
	0x31: InstructionInfo{"sls", "c", 0},
	0x32: InstructionInfo{"sls", "d", 0},
	0x33: InstructionInfo{"sls", "e", 0},
	0x34: InstructionInfo{"sls", "h", 0},
	0x35: InstructionInfo{"sls", "l", 0},
	0x36: InstructionInfo{"sls", "[hl]", 0},
	0x37: InstructionInfo{"sls", "a", 0},
	0x38: InstructionInfo{"srl", "b", 0},
	0x39: InstructionInfo{"srl", "c", 0},
	0x3A: InstructionInfo{"srl", "d", 0},
	0x3B: InstructionInfo{"srl", "e", 0},
	0x3C: InstructionInfo{"srl", "h", 0},
	0x3D: InstructionInfo{"srl", "l", 0},
	0x3E: InstructionInfo{"srl", "[hl]", 0},
	0x3F: InstructionInfo{"srl", "a", 0},
	0x40: InstructionInfo{"bit", "0, b", 0},
	0x41: InstructionInfo{"bit", "0, c", 0},
	0x42: InstructionInfo{"bit", "0, d", 0},
	0x43: InstructionInfo{"bit", "0, e", 0},
	0x44: InstructionInfo{"bit", "0, h", 0},
	0x45: InstructionInfo{"bit", "0, l", 0},
	0x46: InstructionInfo{"bit", "0, [hl]", 0},
	0x47: InstructionInfo{"bit", "0, a", 0},
	0x48: InstructionInfo{"bit", "1, b", 0},
	0x49: InstructionInfo{"bit", "1, c", 0},
	0x4A: InstructionInfo{"bit", "1, d", 0},
	0x4B: InstructionInfo{"bit", "1, e", 0},
	0x4C: InstructionInfo{"bit", "1, h", 0},
	0x4D: InstructionInfo{"bit", "1, l", 0},
	0x4E: InstructionInfo{"bit", "1, [hl]", 0},
	0x4F: InstructionInfo{"bit", "1, a", 0},
	0x50: InstructionInfo{"bit", "2, b", 0},
	0x51: InstructionInfo{"bit", "2, c", 0},
	0x52: InstructionInfo{"bit", "2, d", 0},
	0x53: InstructionInfo{"bit", "2, e", 0},
	0x54: InstructionInfo{"bit", "2, h", 0},
	0x55: InstructionInfo{"bit", "2, l", 0},
	0x56: InstructionInfo{"bit", "2, [hl]", 0},
	0x57: InstructionInfo{"bit", "2, a", 0},
	0x58: InstructionInfo{"bit", "3, b", 0},
	0x59: InstructionInfo{"bit", "3, c", 0},
	0x5A: InstructionInfo{"bit", "3, d", 0},
	0x5B: InstructionInfo{"bit", "3, e", 0},
	0x5C: InstructionInfo{"bit", "3, h", 0},
	0x5D: InstructionInfo{"bit", "3, l", 0},
	0x5E: InstructionInfo{"bit", "3, [hl]", 0},
	0x5F: InstructionInfo{"bit", "3, a", 0},
	0x60: InstructionInfo{"bit", "4, b", 0},
	0x61: InstructionInfo{"bit", "4, c", 0},
	0x62: InstructionInfo{"bit", "4, d", 0},
	0x63: InstructionInfo{"bit", "4, e", 0},
	0x64: InstructionInfo{"bit", "4, h", 0},
	0x65: InstructionInfo{"bit", "4, l", 0},
	0x66: InstructionInfo{"bit", "4, [hl]", 0},
	0x67: InstructionInfo{"bit", "4, a", 0},
	0x68: InstructionInfo{"bit", "5, b", 0},
	0x69: InstructionInfo{"bit", "5, c", 0},
	0x6A: InstructionInfo{"bit", "5, d", 0},
	0x6B: InstructionInfo{"bit", "5, e", 0},
	0x6C: InstructionInfo{"bit", "5, h", 0},
	0x6D: InstructionInfo{"bit", "5, l", 0},
	0x6E: InstructionInfo{"bit", "5, [hl]", 0},
	0x6F: InstructionInfo{"bit", "5, a", 0},
	0x70: InstructionInfo{"bit", "6, b", 0},
	0x71: InstructionInfo{"bit", "6, c", 0},
	0x72: InstructionInfo{"bit", "6, d", 0},
	0x73: InstructionInfo{"bit", "6, e", 0},
	0x74: InstructionInfo{"bit", "6, h", 0},
	0x75: InstructionInfo{"bit", "6, l", 0},
	0x76: InstructionInfo{"bit", "6, [hl]", 0},
	0x77: InstructionInfo{"bit", "6, a", 0},
	0x78: InstructionInfo{"bit", "7, b", 0},
	0x79: InstructionInfo{"bit", "7, c", 0},
	0x7A: InstructionInfo{"bit", "7, d", 0},
	0x7B: InstructionInfo{"bit", "7, e", 0},
	0x7C: InstructionInfo{"bit", "7, h", 0},
	0x7D: InstructionInfo{"bit", "7, l", 0},
	0x7E: InstructionInfo{"bit", "7, [hl]", 0},
	0x7F: InstructionInfo{"bit", "7, a", 0},
	0x80: InstructionInfo{"res", "0, b", 0},
	0x81: InstructionInfo{"res", "0, c", 0},
	0x82: InstructionInfo{"res", "0, d", 0},
	0x83: InstructionInfo{"res", "0, e", 0},
	0x84: InstructionInfo{"res", "0, h", 0},
	0x85: InstructionInfo{"res", "0, l", 0},
	0x86: InstructionInfo{"res", "0, [hl]", 0},
	0x87: InstructionInfo{"res", "0, a", 0},
	0x88: InstructionInfo{"res", "1, b", 0},
	0x89: InstructionInfo{"res", "1, c", 0},
	0x8A: InstructionInfo{"res", "1, d", 0},
	0x8B: InstructionInfo{"res", "1, e", 0},
	0x8C: InstructionInfo{"res", "1, h", 0},
	0x8D: InstructionInfo{"res", "1, l", 0},
	0x8E: InstructionInfo{"res", "1, [hl]", 0},
	0x8F: InstructionInfo{"res", "1, a", 0},
	0x90: InstructionInfo{"res", "2, b", 0},
	0x91: InstructionInfo{"res", "2, c", 0},
	0x92: InstructionInfo{"res", "2, d", 0},
	0x93: InstructionInfo{"res", "2, e", 0},
	0x94: InstructionInfo{"res", "2, h", 0},
	0x95: InstructionInfo{"res", "2, l", 0},
	0x96: InstructionInfo{"res", "2, [hl]", 0},
	0x97: InstructionInfo{"res", "2, a", 0},
	0x98: InstructionInfo{"res", "3, b", 0},
	0x99: InstructionInfo{"res", "3, c", 0},
	0x9A: InstructionInfo{"res", "3, d", 0},
	0x9B: InstructionInfo{"res", "3, e", 0},
	0x9C: InstructionInfo{"res", "3, h", 0},
	0x9D: InstructionInfo{"res", "3, l", 0},
	0x9E: InstructionInfo{"res", "3, [hl]", 0},
	0x9F: InstructionInfo{"res", "3, a", 0},
	0xA0: InstructionInfo{"res", "4, b", 0},
	0xA1: InstructionInfo{"res", "4, c", 0},
	0xA2: InstructionInfo{"res", "4, d", 0},
	0xA3: InstructionInfo{"res", "4, e", 0},
	0xA4: InstructionInfo{"res", "4, h", 0},
	0xA5: InstructionInfo{"res", "4, l", 0},
	0xA6: InstructionInfo{"res", "4, [hl]", 0},
	0xA7: InstructionInfo{"res", "4, a", 0},
	0xA8: InstructionInfo{"res", "5, b", 0},
	0xA9: InstructionInfo{"res", "5, c", 0},
	0xAA: InstructionInfo{"res", "5, d", 0},
	0xAB: InstructionInfo{"res", "5, e", 0},
	0xAC: InstructionInfo{"res", "5, h", 0},
	0xAD: InstructionInfo{"res", "5, l", 0},
	0xAE: InstructionInfo{"res", "5, [hl]", 0},
	0xAF: InstructionInfo{"res", "5, a", 0},
	0xB0: InstructionInfo{"res", "6, b", 0},
	0xB1: InstructionInfo{"res", "6, c", 0},
	0xB2: InstructionInfo{"res", "6, d", 0},
	0xB3: InstructionInfo{"res", "6, e", 0},
	0xB4: InstructionInfo{"res", "6, h", 0},
	0xB5: InstructionInfo{"res", "6, l", 0},
	0xB6: InstructionInfo{"res", "6, [hl]", 0},
	0xB7: InstructionInfo{"res", "6, a", 0},
	0xB8: InstructionInfo{"res", "7, b", 0},
	0xB9: InstructionInfo{"res", "7, c", 0},
	0xBA: InstructionInfo{"res", "7, d", 0},
	0xBB: InstructionInfo{"res", "7, e", 0},
	0xBC: InstructionInfo{"res", "7, h", 0},
	0xBD: InstructionInfo{"res", "7, l", 0},
	0xBE: InstructionInfo{"res", "7, [hl]", 0},
	0xBF: InstructionInfo{"res", "7, a", 0},
	0xC0: InstructionInfo{"set", "0, b", 0},
	0xC1: InstructionInfo{"set", "0, c", 0},
	0xC2: InstructionInfo{"set", "0, d", 0},
	0xC3: InstructionInfo{"set", "0, e", 0},
	0xC4: InstructionInfo{"set", "0, h", 0},
	0xC5: InstructionInfo{"set", "0, l", 0},
	0xC6: InstructionInfo{"set", "0, [hl]", 0},
	0xC7: InstructionInfo{"set", "0, a", 0},
	0xC8: InstructionInfo{"set", "1, b", 0},
	0xC9: InstructionInfo{"set", "1, c", 0},
	0xCA: InstructionInfo{"set", "1, d", 0},
	0xCB: InstructionInfo{"set", "1, e", 0},
	0xCC: InstructionInfo{"set", "1, h", 0},
	0xCD: InstructionInfo{"set", "1, l", 0},
	0xCE: InstructionInfo{"set", "1, [hl]", 0},
	0xCF: InstructionInfo{"set", "1, a", 0},
	0xD0: InstructionInfo{"set", "2, b", 0},
	0xD1: InstructionInfo{"set", "2, c", 0},
	0xD2: InstructionInfo{"set", "2, d", 0},
	0xD3: InstructionInfo{"set", "2, e", 0},
	0xD4: InstructionInfo{"set", "2, h", 0},
	0xD5: InstructionInfo{"set", "2, l", 0},
	0xD6: InstructionInfo{"set", "2, [hl]", 0},
	0xD7: InstructionInfo{"set", "2, a", 0},
	0xD8: InstructionInfo{"set", "3, b", 0},
	0xD9: InstructionInfo{"set", "3, c", 0},
	0xDA: InstructionInfo{"set", "3, d", 0},
	0xDB: InstructionInfo{"set", "3, e", 0},
	0xDC: InstructionInfo{"set", "3, h", 0},
	0xDD: InstructionInfo{"set", "3, l", 0},
	0xDE: InstructionInfo{"set", "3, [hl]", 0},
	0xDF: InstructionInfo{"set", "3, a", 0},
	0xE0: InstructionInfo{"set", "4, b", 0},
	0xE1: InstructionInfo{"set", "4, c", 0},
	0xE2: InstructionInfo{"set", "4, d", 0},
	0xE3: InstructionInfo{"set", "4, e", 0},
	0xE4: InstructionInfo{"set", "4, h", 0},
	0xE5: InstructionInfo{"set", "4, l", 0},
	0xE6: InstructionInfo{"set", "4, [hl]", 0},
	0xE7: InstructionInfo{"set", "4, a", 0},
	0xE8: InstructionInfo{"set", "5, b", 0},
	0xE9: InstructionInfo{"set", "5, c", 0},
	0xEA: InstructionInfo{"set", "5, d", 0},
	0xEB: InstructionInfo{"set", "5, e", 0},
	0xEC: InstructionInfo{"set", "5, h", 0},
	0xED: InstructionInfo{"set", "5, l", 0},
	0xEE: InstructionInfo{"set", "5, [hl]", 0},
	0xEF: InstructionInfo{"set", "5, a", 0},
	0xF0: InstructionInfo{"set", "6, b", 0},
	0xF1: InstructionInfo{"set", "6, c", 0},
	0xF2: InstructionInfo{"set", "6, d", 0},
	0xF3: InstructionInfo{"set", "6, e", 0},
	0xF4: InstructionInfo{"set", "6, h", 0},
	0xF5: InstructionInfo{"set", "6, l", 0},
	0xF6: InstructionInfo{"set", "6, [hl]", 0},
	0xF7: InstructionInfo{"set", "6, a", 0},
	0xF8: InstructionInfo{"set", "7, b", 0},
	0xF9: InstructionInfo{"set", "7, c", 0},
	0xFA: InstructionInfo{"set", "7, d", 0},
	0xFB: InstructionInfo{"set", "7, e", 0},
	0xFC: InstructionInfo{"set", "7, h", 0},
	0xFD: InstructionInfo{"set", "7, l", 0},
	0xFE: InstructionInfo{"set", "7, [hl]", 0},
	0xFF: InstructionInfo{"set", "7, a", 0},
}

var DisassemblyTable_DD = map[uint8]InstructionInfo {
	0x09: InstructionInfo{"add", "ix, bc", 0},
	0x19: InstructionInfo{"add", "ix, de", 0},
	0x21: InstructionInfo{"ld", "ix, %d16", 2},
	0x22: InstructionInfo{"ld", "[%d16], ix", 2},
	0x23: InstructionInfo{"inc", "ix", 0},
	0x24: InstructionInfo{"inc", "ixh", 0},
	0x25: InstructionInfo{"dec", "ixh", 0},
	0x26: InstructionInfo{"ld", "ixh, %d8", 1},
	0x29: InstructionInfo{"add", "ix, ix", 0},
	0x2A: InstructionInfo{"ld", "ix, [%d16]", 2},
	0x2B: InstructionInfo{"dec", "ix", 0},
	0x2C: InstructionInfo{"inc", "ixl", 0},
	0x2D: InstructionInfo{"dec", "ixl", 0},
	0x2E: InstructionInfo{"ld", "ixl, %d8", 1},
	0x34: InstructionInfo{"inc", "[ix+%d8]", 1},
	0x35: InstructionInfo{"dec", "[ix+%d8]", 1},
	0x36: InstructionInfo{"ld", "[ix+%d8], %d8", 2},
	0x39: InstructionInfo{"add", "ix, sp", 0},
	0x44: InstructionInfo{"ld", "b, ixh", 0},
	0x45: InstructionInfo{"ld", "b, ixl", 0},
	0x46: InstructionInfo{"ld", "b, [ix+%d8]", 1},
	0x4C: InstructionInfo{"ld", "c, ixh", 0},
	0x4D: InstructionInfo{"ld", "c, ixl", 0},
	0x4E: InstructionInfo{"ld", "c, [ix+%d8]", 1},
	0x54: InstructionInfo{"ld", "d, ixh", 0},
	0x55: InstructionInfo{"ld", "d, ixl", 0},
	0x56: InstructionInfo{"ld", "d, [ix+%d8]", 1},
	0x5C: InstructionInfo{"ld", "e, ixh", 0},
	0x5D: InstructionInfo{"ld", "e, ixl", 0},
	0x5E: InstructionInfo{"ld", "e, [ix+%d8]", 1},
	0x60: InstructionInfo{"ld", "ixh, b", 0},
	0x61: InstructionInfo{"ld", "ixh, c", 0},
	0x62: InstructionInfo{"ld", "ixh, d", 0},
	0x63: InstructionInfo{"ld", "ixh, e", 0},
	0x64: InstructionInfo{"ld", "ixh, ixh", 0},
	0x65: InstructionInfo{"ld", "ixh, ixl", 0},
	0x66: InstructionInfo{"ld", "h, [ix+%d8]", 1},
	0x67: InstructionInfo{"ld", "ixh, a", 0},
	0x68: InstructionInfo{"ld", "ixl, b", 0},
	0x69: InstructionInfo{"ld", "ixl, c", 0},
	0x6A: InstructionInfo{"ld", "ixl, d", 0},
	0x6B: InstructionInfo{"ld", "ixl, e", 0},
	0x6C: InstructionInfo{"ld", "ixl, ixh", 0},
	0x6D: InstructionInfo{"ld", "ixl, ixl", 0},
	0x6E: InstructionInfo{"ld", "l, [ix+%d8]", 1},
	0x6F: InstructionInfo{"ld", "ixl, a", 0},
	0x70: InstructionInfo{"ld", "[ix+%d8], b", 1},
	0x71: InstructionInfo{"ld", "[ix+%d8], c", 1},
	0x72: InstructionInfo{"ld", "[ix+%d8], d", 1},
	0x73: InstructionInfo{"ld", "[ix+%d8], e", 1},
	0x74: InstructionInfo{"ld", "[ix+%d8], h", 1},
	0x75: InstructionInfo{"ld", "[ix+%d8], l", 1},
	0x77: InstructionInfo{"ld", "[ix+%d8], a", 1},
	0x7C: InstructionInfo{"ld", "a, ixh", 0},
	0x7D: InstructionInfo{"ld", "a, ixl", 0},
	0x7E: InstructionInfo{"ld", "a, [ix+%d8]", 1},
	0x84: InstructionInfo{"add", "a, ixh", 0},
	0x85: InstructionInfo{"add", "a, ixl", 0},
	0x86: InstructionInfo{"add", "a, [ix+%d8]", 1},
	0x8C: InstructionInfo{"adc", "a, ixh", 0},
	0x8D: InstructionInfo{"adc", "a, ixl", 0},
	0x8E: InstructionInfo{"adc", "a, [ix+%d8]", 1},
	0x94: InstructionInfo{"sub", "a, ixh", 0},
	0x95: InstructionInfo{"sub", "a, ixl", 0},
	0x96: InstructionInfo{"sub", "a, [ix+%d8]", 1},
	0x9C: InstructionInfo{"sbc", "a, ixh", 0},
	0x9D: InstructionInfo{"sbc", "a, ixl", 0},
	0x9E: InstructionInfo{"sbc", "a, [ix+%d8]", 1},
	0xA4: InstructionInfo{"and", "ixh", 0},
	0xA5: InstructionInfo{"and", "ixl", 0},
	0xA6: InstructionInfo{"and", "[ix+%d8]", 1},
	0xAC: InstructionInfo{"xor", "ixh", 0},
	0xAD: InstructionInfo{"xor", "ixl", 0},
	0xAE: InstructionInfo{"xor", "[ix+%d8]", 1},
	0xB4: InstructionInfo{"or", "ixh", 0},
	0xB5: InstructionInfo{"or", "ixl", 0},
	0xB6: InstructionInfo{"or", "[ix+%d8]", 1},
	0xBC: InstructionInfo{"cp", "ixh", 0},
	0xBD: InstructionInfo{"cp", "ixl", 0},
	0xBE: InstructionInfo{"cp", "[ix+%d8]", 1},
	0xE1: InstructionInfo{"pop", "ix", 0},
	0xE3: InstructionInfo{"ex", "[sp], ix", 0},
	0xE5: InstructionInfo{"push", "ix", 0},
	0xE9: InstructionInfo{"jp", "[ix]", 0},
}

var DisassemblyTable_ED = map[uint8]InstructionInfo {
	0x40: InstructionInfo{"in", "b, [c]", 0},
	0x41: InstructionInfo{"out", "[c], b", 0},
	0x42: InstructionInfo{"sbc", "hl, bc", 0},
	0x43: InstructionInfo{"ld", "[%d16], bc", 2},
	0x44: InstructionInfo{"neg", "", 0},
	0x45: InstructionInfo{"retn", "", 0},
	0x46: InstructionInfo{"im", "0", 0},
	0x47: InstructionInfo{"ld", "i, a", 0},
	0x48: InstructionInfo{"in", "c, [c]", 0},
	0x49: InstructionInfo{"out", "[c], c", 0},
	0x4A: InstructionInfo{"adc", "hl, bc", 0},
	0x4B: InstructionInfo{"ld", "bc, [%d16]", 2},
	0x4D: InstructionInfo{"reti", "", 0},
	0x4F: InstructionInfo{"ld", "r, a", 0},
	0x50: InstructionInfo{"in", "d, [c]", 0},
	0x51: InstructionInfo{"out", "[c], d", 0},
	0x52: InstructionInfo{"sbc", "hl, de", 0},
	0x53: InstructionInfo{"ld", "[%d16], de", 2},
	0x56: InstructionInfo{"im", "1", 0},
	0x57: InstructionInfo{"ld", "a, i", 0},
	0x58: InstructionInfo{"in", "e, [c]", 0},
	0x59: InstructionInfo{"out", "[c], e", 0},
	0x5A: InstructionInfo{"adc", "hl, de", 0},
	0x5B: InstructionInfo{"ld", "de, [%d16]", 2},
	0x5E: InstructionInfo{"im", "2", 0},
	0x5F: InstructionInfo{"ld", "a, r", 0},
	0x60: InstructionInfo{"in", "h, [c]", 0},
	0x61: InstructionInfo{"out", "[c], h", 0},
	0x62: InstructionInfo{"sbc", "hl, hl", 0},
	0x63: InstructionInfo{"ld", "[%d16], hl", 2},
	0x67: InstructionInfo{"rrd", "", 0},
	0x68: InstructionInfo{"in", "l, [c]", 0},
	0x69: InstructionInfo{"out", "[c], l", 0},
	0x6A: InstructionInfo{"adc", "hl, hl", 0},
	0x6B: InstructionInfo{"ld", "hl, [%d16]", 2},
	0x6F: InstructionInfo{"rld", "", 0},
	0x70: InstructionInfo{"in", "f, [c]", 0},
	0x71: InstructionInfo{"out", "[c], f", 0},
	0x72: InstructionInfo{"sbc", "hl, sp", 0},
	0x73: InstructionInfo{"ld", "[%d16], sp", 2},
	0x78: InstructionInfo{"in", "a, [c]", 0},
	0x79: InstructionInfo{"out", "[c], a", 0},
	0x7A: InstructionInfo{"adc", "hl, sp", 0},
	0x7B: InstructionInfo{"ld", "sp, [%d16]", 2},
	0x7E: InstructionInfo{"im", "2", 0},
	0xA0: InstructionInfo{"ldi", "", 0},
	0xA1: InstructionInfo{"cpi", "", 0},
	0xA2: InstructionInfo{"ini", "", 0},
	0xA3: InstructionInfo{"oti", "", 0},
	0xA8: InstructionInfo{"ldd", "", 0},
	0xA9: InstructionInfo{"cpd", "", 0},
	0xAA: InstructionInfo{"ind", "", 0},
	0xAB: InstructionInfo{"otd", "", 0},
	0xB0: InstructionInfo{"ldir", "", 0},
	0xB1: InstructionInfo{"cpir", "", 0},
	0xB2: InstructionInfo{"inir", "", 0},
	0xB3: InstructionInfo{"otir", "", 0},
	0xB8: InstructionInfo{"lddr", "", 0},
	0xB9: InstructionInfo{"cpdr", "", 0},
	0xBA: InstructionInfo{"indr", "", 0},
	0xBB: InstructionInfo{"otdr", "", 0},
}

var DisassemblyTable_FD = map[uint8]InstructionInfo {
	0x09: InstructionInfo{"add", "iy, bc", 0},
	0x19: InstructionInfo{"add", "iy, de", 0},
	0x21: InstructionInfo{"ld", "iy, %d16", 2},
	0x22: InstructionInfo{"ld", "[%d16], iy", 2},
	0x23: InstructionInfo{"inc", "iy", 0},
	0x24: InstructionInfo{"inc", "iyh", 0},
	0x25: InstructionInfo{"dec", "iyh", 0},
	0x26: InstructionInfo{"ld", "iyh, %d8", 1},
	0x29: InstructionInfo{"add", "iy, iy", 0},
	0x2A: InstructionInfo{"ld", "iy, [%d16]", 2},
	0x2B: InstructionInfo{"dec", "iy", 0},
	0x2C: InstructionInfo{"inc", "iyl", 0},
	0x2D: InstructionInfo{"dec", "iyl", 0},
	0x2E: InstructionInfo{"ld", "iyl, %d8", 1},
	0x34: InstructionInfo{"inc", "[iy+%d8]", 1},
	0x35: InstructionInfo{"dec", "[iy+%d8]", 1},
	0x36: InstructionInfo{"ld", "[iy+%d8], %d8", 2},
	0x39: InstructionInfo{"add", "iy, sp", 0},
	0x44: InstructionInfo{"ld", "b, iyh", 0},
	0x45: InstructionInfo{"ld", "b, iyl", 0},
	0x46: InstructionInfo{"ld", "b, [iy+%d8]", 1},
	0x4C: InstructionInfo{"ld", "c, iyh", 0},
	0x4D: InstructionInfo{"ld", "c, iyl", 0},
	0x4E: InstructionInfo{"ld", "c, [iy+%d8]", 1},
	0x54: InstructionInfo{"ld", "d, iyh", 0},
	0x55: InstructionInfo{"ld", "d, iyl", 0},
	0x56: InstructionInfo{"ld", "d, [iy+%d8]", 1},
	0x5C: InstructionInfo{"ld", "e, iyh", 0},
	0x5D: InstructionInfo{"ld", "e, iyl", 0},
	0x5E: InstructionInfo{"ld", "e, [iy+%d8]", 1},
	0x60: InstructionInfo{"ld", "iyh, b", 0},
	0x61: InstructionInfo{"ld", "iyh, c", 0},
	0x62: InstructionInfo{"ld", "iyh, d", 0},
	0x63: InstructionInfo{"ld", "iyh, e", 0},
	0x64: InstructionInfo{"ld", "iyh, iyh", 0},
	0x65: InstructionInfo{"ld", "iyh, iyl", 0},
	0x66: InstructionInfo{"ld", "h, [iy+%d8]", 1},
	0x67: InstructionInfo{"ld", "iyh, a", 0},
	0x68: InstructionInfo{"ld", "iyl, b", 0},
	0x69: InstructionInfo{"ld", "iyl, c", 0},
	0x6A: InstructionInfo{"ld", "iyl, d", 0},
	0x6B: InstructionInfo{"ld", "iyl, e", 0},
	0x6C: InstructionInfo{"ld", "iyl, iyh", 0},
	0x6D: InstructionInfo{"ld", "iyl, iyl", 0},
	0x6E: InstructionInfo{"ld", "l, [iy+%d8]", 1},
	0x6F: InstructionInfo{"ld", "iyl, a", 0},
	0x70: InstructionInfo{"ld", "[iy+%d8], b", 1},
	0x71: InstructionInfo{"ld", "[iy+%d8], c", 1},
	0x72: InstructionInfo{"ld", "[iy+%d8], d", 1},
	0x73: InstructionInfo{"ld", "[iy+%d8], e", 1},
	0x74: InstructionInfo{"ld", "[iy+%d8], h", 1},
	0x75: InstructionInfo{"ld", "[iy+%d8], l", 1},
	0x77: InstructionInfo{"ld", "[iy+%d8], a", 1},
	0x7C: InstructionInfo{"ld", "a, iyh", 0},
	0x7D: InstructionInfo{"ld", "a, iyl", 0},
	0x7E: InstructionInfo{"ld", "a, [iy+%d8]", 1},
	0x84: InstructionInfo{"add", "a, iyh", 0},
	0x85: InstructionInfo{"add", "a, iyl", 0},
	0x86: InstructionInfo{"add", "a, [iy+%d8]", 1},
	0x8C: InstructionInfo{"adc", "a, iyh", 0},
	0x8D: InstructionInfo{"adc", "a, iyl", 0},
	0x8E: InstructionInfo{"adc", "a, [iy+%d8]", 1},
	0x94: InstructionInfo{"sub", "a, iyh", 0},
	0x95: InstructionInfo{"sub", "a, iyl", 0},
	0x96: InstructionInfo{"sub", "a, [iy+%d8]", 1},
	0x9C: InstructionInfo{"sbc", "a, iyh", 0},
	0x9D: InstructionInfo{"sbc", "a, iyl", 0},
	0x9E: InstructionInfo{"sbc", "a, [iy+%d8]", 1},
	0xA4: InstructionInfo{"and", "iyh", 0},
	0xA5: InstructionInfo{"and", "iyl", 0},
	0xA6: InstructionInfo{"and", "[iy+%d8]", 1},
	0xAC: InstructionInfo{"xor", "iyh", 0},
	0xAD: InstructionInfo{"xor", "iyl", 0},
	0xAE: InstructionInfo{"xor", "[iy+%d8]", 1},
	0xB4: InstructionInfo{"or", "iyh", 0},
	0xB5: InstructionInfo{"or", "iyl", 0},
	0xB6: InstructionInfo{"or", "[iy+%d8]", 1},
	0xBC: InstructionInfo{"cp", "iyh", 0},
	0xBD: InstructionInfo{"cp", "iyl", 0},
	0xBE: InstructionInfo{"cp", "[iy+%d8]", 1},
	0xE1: InstructionInfo{"pop", "iy", 0},
	0xE3: InstructionInfo{"ex", "[sp], iy", 0},
	0xE5: InstructionInfo{"push", "iy", 0},
	0xE9: InstructionInfo{"jp", "[iy]", 0},
}

var DisassemblyTable_DDCB = map[uint8]InstructionInfo{
	0x00: InstructionInfo{"rlc", "[ix+%ds8]->b", 1},
	0x01: InstructionInfo{"rlc", "[ix+%ds8]->c", 1},
	0x02: InstructionInfo{"rlc", "[ix+%ds8]->d", 1},
	0x03: InstructionInfo{"rlc", "[ix+%ds8]->e", 1},
	0x04: InstructionInfo{"rlc", "[ix+%ds8]->h", 1},
	0x05: InstructionInfo{"rlc", "[ix+%ds8]->l", 1},
	0x06: InstructionInfo{"rlc", "[ix+%ds8]", 1},
	0x07: InstructionInfo{"rlc", "[ix+%ds8]->a", 1},
	0x08: InstructionInfo{"rrc", "[ix+%ds8]->b", 1},
	0x09: InstructionInfo{"rrc", "[ix+%ds8]->c", 1},
	0x0A: InstructionInfo{"rrc", "[ix+%ds8]->d", 1},
	0x0B: InstructionInfo{"rrc", "[ix+%ds8]->e", 1},
	0x0C: InstructionInfo{"rrc", "[ix+%ds8]->h", 1},
	0x0D: InstructionInfo{"rrc", "[ix+%ds8]->l", 1},
	0x0E: InstructionInfo{"rrc", "[ix+%ds8]", 1},
	0x0F: InstructionInfo{"rrc", "[ix+%ds8]->a", 1},
	0x10: InstructionInfo{"rl", "[ix+%ds8]->b", 1},
	0x11: InstructionInfo{"rl", "[ix+%ds8]->c", 1},
	0x12: InstructionInfo{"rl", "[ix+%ds8]->d", 1},
	0x13: InstructionInfo{"rl", "[ix+%ds8]->e", 1},
	0x14: InstructionInfo{"rl", "[ix+%ds8]->h", 1},
	0x15: InstructionInfo{"rl", "[ix+%ds8]->l", 1},
	0x16: InstructionInfo{"rl", "[ix+%ds8]", 1},
	0x17: InstructionInfo{"rl", "[ix+%ds8]->a", 1},
	0x18: InstructionInfo{"rr", "[ix+%ds8]->b", 1},
	0x19: InstructionInfo{"rr", "[ix+%ds8]->c", 1},
	0x1A: InstructionInfo{"rr", "[ix+%ds8]->d", 1},
	0x1B: InstructionInfo{"rr", "[ix+%ds8]->e", 1},
	0x1C: InstructionInfo{"rr", "[ix+%ds8]->h", 1},
	0x1D: InstructionInfo{"rr", "[ix+%ds8]->l", 1},
	0x1E: InstructionInfo{"rr", "[ix+%ds8]", 1},
	0x1F: InstructionInfo{"rr", "[ix+%ds8]->a", 1},
	0x20: InstructionInfo{"sla", "[ix+%ds8]->b", 1},
	0x21: InstructionInfo{"sla", "[ix+%ds8]->c", 1},
	0x22: InstructionInfo{"sla", "[ix+%ds8]->d", 1},
	0x23: InstructionInfo{"sla", "[ix+%ds8]->e", 1},
	0x24: InstructionInfo{"sla", "[ix+%ds8]->h", 1},
	0x25: InstructionInfo{"sla", "[ix+%ds8]->l", 1},
	0x26: InstructionInfo{"sla", "[ix+%ds8]", 1},
	0x27: InstructionInfo{"sla", "[ix+%ds8]->a", 1},
	0x28: InstructionInfo{"sra", "[ix+%ds8]->b", 1},
	0x29: InstructionInfo{"sra", "[ix+%ds8]->c", 1},
	0x2A: InstructionInfo{"sra", "[ix+%ds8]->d", 1},
	0x2B: InstructionInfo{"sra", "[ix+%ds8]->e", 1},
	0x2C: InstructionInfo{"sra", "[ix+%ds8]->h", 1},
	0x2D: InstructionInfo{"sra", "[ix+%ds8]->l", 1},
	0x2E: InstructionInfo{"sra", "[ix+%ds8]", 1},
	0x2F: InstructionInfo{"sra", "[ix+%ds8]->a", 1},
	0x30: InstructionInfo{"sls", "[ix+%ds8]->b", 1},
	0x31: InstructionInfo{"sls", "[ix+%ds8]->c", 1},
	0x32: InstructionInfo{"sls", "[ix+%ds8]->d", 1},
	0x33: InstructionInfo{"sls", "[ix+%ds8]->e", 1},
	0x34: InstructionInfo{"sls", "[ix+%ds8]->h", 1},
	0x35: InstructionInfo{"sls", "[ix+%ds8]->l", 1},
	0x36: InstructionInfo{"sls", "[ix+%ds8]", 1},
	0x37: InstructionInfo{"sls", "[ix+%ds8]->a", 1},
	0x38: InstructionInfo{"srl", "[ix+%ds8]->b", 1},
	0x39: InstructionInfo{"srl", "[ix+%ds8]->c", 1},
	0x3A: InstructionInfo{"srl", "[ix+%ds8]->d", 1},
	0x3B: InstructionInfo{"srl", "[ix+%ds8]->e", 1},
	0x3C: InstructionInfo{"srl", "[ix+%ds8]->h", 1},
	0x3D: InstructionInfo{"srl", "[ix+%ds8]->l", 1},
	0x3E: InstructionInfo{"srl", "[ix+%ds8]", 1},
	0x3F: InstructionInfo{"srl", "[ix+%ds8]->a", 1},
	0x40: InstructionInfo{"bit", "0, [ix+%ds8]->b", 1},
	0x41: InstructionInfo{"bit", "0, [ix+%ds8]->c", 1},
	0x42: InstructionInfo{"bit", "0, [ix+%ds8]->d", 1},
	0x43: InstructionInfo{"bit", "0, [ix+%ds8]->e", 1},
	0x44: InstructionInfo{"bit", "0, [ix+%ds8]->h", 1},
	0x45: InstructionInfo{"bit", "0, [ix+%ds8]->l", 1},
	0x46: InstructionInfo{"bit", "0, [ix+%ds8]", 1},
	0x47: InstructionInfo{"bit", "0, [ix+%ds8]->a", 1},
	0x48: InstructionInfo{"bit", "1, [ix+%ds8]->b", 1},
	0x49: InstructionInfo{"bit", "1, [ix+%ds8]->c", 1},
	0x4A: InstructionInfo{"bit", "1, [ix+%ds8]->d", 1},
	0x4B: InstructionInfo{"bit", "1, [ix+%ds8]->e", 1},
	0x4C: InstructionInfo{"bit", "1, [ix+%ds8]->h", 1},
	0x4D: InstructionInfo{"bit", "1, [ix+%ds8]->l", 1},
	0x4E: InstructionInfo{"bit", "1, [ix+%ds8]", 1},
	0x4F: InstructionInfo{"bit", "1, [ix+%ds8]->a", 1},
	0x50: InstructionInfo{"bit", "2, [ix+%ds8]->b", 1},
	0x51: InstructionInfo{"bit", "2, [ix+%ds8]->c", 1},
	0x52: InstructionInfo{"bit", "2, [ix+%ds8]->d", 1},
	0x53: InstructionInfo{"bit", "2, [ix+%ds8]->e", 1},
	0x54: InstructionInfo{"bit", "2, [ix+%ds8]->h", 1},
	0x55: InstructionInfo{"bit", "2, [ix+%ds8]->l", 1},
	0x56: InstructionInfo{"bit", "2, [ix+%ds8]", 1},
	0x57: InstructionInfo{"bit", "2, [ix+%ds8]->a", 1},
	0x58: InstructionInfo{"bit", "3, [ix+%ds8]->b", 1},
	0x59: InstructionInfo{"bit", "3, [ix+%ds8]->c", 1},
	0x5A: InstructionInfo{"bit", "3, [ix+%ds8]->d", 1},
	0x5B: InstructionInfo{"bit", "3, [ix+%ds8]->e", 1},
	0x5C: InstructionInfo{"bit", "3, [ix+%ds8]->h", 1},
	0x5D: InstructionInfo{"bit", "3, [ix+%ds8]->l", 1},
	0x5E: InstructionInfo{"bit", "3, [ix+%ds8]", 1},
	0x5F: InstructionInfo{"bit", "3, [ix+%ds8]->a", 1},
	0x60: InstructionInfo{"bit", "4, [ix+%ds8]->b", 1},
	0x61: InstructionInfo{"bit", "4, [ix+%ds8]->c", 1},
	0x62: InstructionInfo{"bit", "4, [ix+%ds8]->d", 1},
	0x63: InstructionInfo{"bit", "4, [ix+%ds8]->e", 1},
	0x64: InstructionInfo{"bit", "4, [ix+%ds8]->h", 1},
	0x65: InstructionInfo{"bit", "4, [ix+%ds8]->l", 1},
	0x66: InstructionInfo{"bit", "4, [ix+%ds8]", 1},
	0x67: InstructionInfo{"bit", "4, [ix+%ds8]->a", 1},
	0x68: InstructionInfo{"bit", "5, [ix+%ds8]->b", 1},
	0x69: InstructionInfo{"bit", "5, [ix+%ds8]->c", 1},
	0x6A: InstructionInfo{"bit", "5, [ix+%ds8]->d", 1},
	0x6B: InstructionInfo{"bit", "5, [ix+%ds8]->e", 1},
	0x6C: InstructionInfo{"bit", "5, [ix+%ds8]->h", 1},
	0x6D: InstructionInfo{"bit", "5, [ix+%ds8]->l", 1},
	0x6E: InstructionInfo{"bit", "5, [ix+%ds8]", 1},
	0x6F: InstructionInfo{"bit", "5, [ix+%ds8]->a", 1},
	0x70: InstructionInfo{"bit", "6, [ix+%ds8]->b", 1},
	0x71: InstructionInfo{"bit", "6, [ix+%ds8]->c", 1},
	0x72: InstructionInfo{"bit", "6, [ix+%ds8]->d", 1},
	0x73: InstructionInfo{"bit", "6, [ix+%ds8]->e", 1},
	0x74: InstructionInfo{"bit", "6, [ix+%ds8]->h", 1},
	0x75: InstructionInfo{"bit", "6, [ix+%ds8]->l", 1},
	0x76: InstructionInfo{"bit", "6, [ix+%ds8]", 1},
	0x77: InstructionInfo{"bit", "6, [ix+%ds8]->a", 1},
	0x78: InstructionInfo{"bit", "7, [ix+%ds8]->b", 1},
	0x79: InstructionInfo{"bit", "7, [ix+%ds8]->c", 1},
	0x7A: InstructionInfo{"bit", "7, [ix+%ds8]->d", 1},
	0x7B: InstructionInfo{"bit", "7, [ix+%ds8]->e", 1},
	0x7C: InstructionInfo{"bit", "7, [ix+%ds8]->h", 1},
	0x7D: InstructionInfo{"bit", "7, [ix+%ds8]->l", 1},
	0x7E: InstructionInfo{"bit", "7, [ix+%ds8]", 1},
	0x7F: InstructionInfo{"bit", "7, [ix+%ds8]->a", 1},
	0x80: InstructionInfo{"res", "0, [ix+%ds8]->b", 1},
	0x81: InstructionInfo{"res", "0, [ix+%ds8]->c", 1},
	0x82: InstructionInfo{"res", "0, [ix+%ds8]->d", 1},
	0x83: InstructionInfo{"res", "0, [ix+%ds8]->e", 1},
	0x84: InstructionInfo{"res", "0, [ix+%ds8]->h", 1},
	0x85: InstructionInfo{"res", "0, [ix+%ds8]->l", 1},
	0x86: InstructionInfo{"res", "0, [ix+%ds8]", 1},
	0x87: InstructionInfo{"res", "0, [ix+%ds8]->a", 1},
	0x88: InstructionInfo{"res", "1, [ix+%ds8]->b", 1},
	0x89: InstructionInfo{"res", "1, [ix+%ds8]->c", 1},
	0x8A: InstructionInfo{"res", "1, [ix+%ds8]->d", 1},
	0x8B: InstructionInfo{"res", "1, [ix+%ds8]->e", 1},
	0x8C: InstructionInfo{"res", "1, [ix+%ds8]->h", 1},
	0x8D: InstructionInfo{"res", "1, [ix+%ds8]->l", 1},
	0x8E: InstructionInfo{"res", "1, [ix+%ds8]", 1},
	0x8F: InstructionInfo{"res", "1, [ix+%ds8]->a", 1},
	0x90: InstructionInfo{"res", "2, [ix+%ds8]->b", 1},
	0x91: InstructionInfo{"res", "2, [ix+%ds8]->c", 1},
	0x92: InstructionInfo{"res", "2, [ix+%ds8]->d", 1},
	0x93: InstructionInfo{"res", "2, [ix+%ds8]->e", 1},
	0x94: InstructionInfo{"res", "2, [ix+%ds8]->h", 1},
	0x95: InstructionInfo{"res", "2, [ix+%ds8]->l", 1},
	0x96: InstructionInfo{"res", "2, [ix+%ds8]", 1},
	0x97: InstructionInfo{"res", "2, [ix+%ds8]->a", 1},
	0x98: InstructionInfo{"res", "3, [ix+%ds8]->b", 1},
	0x99: InstructionInfo{"res", "3, [ix+%ds8]->c", 1},
	0x9A: InstructionInfo{"res", "3, [ix+%ds8]->d", 1},
	0x9B: InstructionInfo{"res", "3, [ix+%ds8]->e", 1},
	0x9C: InstructionInfo{"res", "3, [ix+%ds8]->h", 1},
	0x9D: InstructionInfo{"res", "3, [ix+%ds8]->l", 1},
	0x9E: InstructionInfo{"res", "3, [ix+%ds8]", 1},
	0x9F: InstructionInfo{"res", "3, [ix+%ds8]->a", 1},
	0xA0: InstructionInfo{"res", "4, [ix+%ds8]->b", 1},
	0xA1: InstructionInfo{"res", "4, [ix+%ds8]->c", 1},
	0xA2: InstructionInfo{"res", "4, [ix+%ds8]->d", 1},
	0xA3: InstructionInfo{"res", "4, [ix+%ds8]->e", 1},
	0xA4: InstructionInfo{"res", "4, [ix+%ds8]->h", 1},
	0xA5: InstructionInfo{"res", "4, [ix+%ds8]->l", 1},
	0xA6: InstructionInfo{"res", "4, [ix+%ds8]", 1},
	0xA7: InstructionInfo{"res", "4, [ix+%ds8]->a", 1},
	0xA8: InstructionInfo{"res", "5, [ix+%ds8]->b", 1},
	0xA9: InstructionInfo{"res", "5, [ix+%ds8]->c", 1},
	0xAA: InstructionInfo{"res", "5, [ix+%ds8]->d", 1},
	0xAB: InstructionInfo{"res", "5, [ix+%ds8]->e", 1},
	0xAC: InstructionInfo{"res", "5, [ix+%ds8]->h", 1},
	0xAD: InstructionInfo{"res", "5, [ix+%ds8]->l", 1},
	0xAE: InstructionInfo{"res", "5, [ix+%ds8]", 1},
	0xAF: InstructionInfo{"res", "5, [ix+%ds8]->a", 1},
	0xB0: InstructionInfo{"res", "6, [ix+%ds8]->b", 1},
	0xB1: InstructionInfo{"res", "6, [ix+%ds8]->c", 1},
	0xB2: InstructionInfo{"res", "6, [ix+%ds8]->d", 1},
	0xB3: InstructionInfo{"res", "6, [ix+%ds8]->e", 1},
	0xB4: InstructionInfo{"res", "6, [ix+%ds8]->h", 1},
	0xB5: InstructionInfo{"res", "6, [ix+%ds8]->l", 1},
	0xB6: InstructionInfo{"res", "6, [ix+%ds8]", 1},
	0xB7: InstructionInfo{"res", "6, [ix+%ds8]->a", 1},
	0xB8: InstructionInfo{"res", "7, [ix+%ds8]->b", 1},
	0xB9: InstructionInfo{"res", "7, [ix+%ds8]->c", 1},
	0xBA: InstructionInfo{"res", "7, [ix+%ds8]->d", 1},
	0xBB: InstructionInfo{"res", "7, [ix+%ds8]->e", 1},
	0xBC: InstructionInfo{"res", "7, [ix+%ds8]->h", 1},
	0xBD: InstructionInfo{"res", "7, [ix+%ds8]->l", 1},
	0xBE: InstructionInfo{"res", "7, [ix+%ds8]", 1},
	0xBF: InstructionInfo{"res", "7, [ix+%ds8]->a", 1},
	0xC0: InstructionInfo{"set", "0, [ix+%ds8]->b", 1},
	0xC1: InstructionInfo{"set", "0, [ix+%ds8]->c", 1},
	0xC2: InstructionInfo{"set", "0, [ix+%ds8]->d", 1},
	0xC3: InstructionInfo{"set", "0, [ix+%ds8]->e", 1},
	0xC4: InstructionInfo{"set", "0, [ix+%ds8]->h", 1},
	0xC5: InstructionInfo{"set", "0, [ix+%ds8]->l", 1},
	0xC6: InstructionInfo{"set", "0, [ix+%ds8]", 1},
	0xC7: InstructionInfo{"set", "0, [ix+%ds8]->a", 1},
	0xC8: InstructionInfo{"set", "1, [ix+%ds8]->b", 1},
	0xC9: InstructionInfo{"set", "1, [ix+%ds8]->c", 1},
	0xCA: InstructionInfo{"set", "1, [ix+%ds8]->d", 1},
	0xCB: InstructionInfo{"set", "1, [ix+%ds8]->e", 1},
	0xCC: InstructionInfo{"set", "1, [ix+%ds8]->h", 1},
	0xCD: InstructionInfo{"set", "1, [ix+%ds8]->l", 1},
	0xCE: InstructionInfo{"set", "1, [ix+%ds8]", 1},
	0xCF: InstructionInfo{"set", "1, [ix+%ds8]->a", 1},
	0xD0: InstructionInfo{"set", "2, [ix+%ds8]->b", 1},
	0xD1: InstructionInfo{"set", "2, [ix+%ds8]->c", 1},
	0xD2: InstructionInfo{"set", "2, [ix+%ds8]->d", 1},
	0xD3: InstructionInfo{"set", "2, [ix+%ds8]->e", 1},
	0xD4: InstructionInfo{"set", "2, [ix+%ds8]->h", 1},
	0xD5: InstructionInfo{"set", "2, [ix+%ds8]->l", 1},
	0xD6: InstructionInfo{"set", "2, [ix+%ds8]", 1},
	0xD7: InstructionInfo{"set", "2, [ix+%ds8]->a", 1},
	0xD8: InstructionInfo{"set", "3, [ix+%ds8]->b", 1},
	0xD9: InstructionInfo{"set", "3, [ix+%ds8]->c", 1},
	0xDA: InstructionInfo{"set", "3, [ix+%ds8]->d", 1},
	0xDB: InstructionInfo{"set", "3, [ix+%ds8]->e", 1},
	0xDC: InstructionInfo{"set", "3, [ix+%ds8]->h", 1},
	0xDD: InstructionInfo{"set", "3, [ix+%ds8]->l", 1},
	0xDE: InstructionInfo{"set", "3, [ix+%ds8]", 1},
	0xDF: InstructionInfo{"set", "3, [ix+%ds8]->a", 1},
	0xE0: InstructionInfo{"set", "4, [ix+%ds8]->b", 1},
	0xE1: InstructionInfo{"set", "4, [ix+%ds8]->c", 1},
	0xE2: InstructionInfo{"set", "4, [ix+%ds8]->d", 1},
	0xE3: InstructionInfo{"set", "4, [ix+%ds8]->e", 1},
	0xE4: InstructionInfo{"set", "4, [ix+%ds8]->h", 1},
	0xE5: InstructionInfo{"set", "4, [ix+%ds8]->l", 1},
	0xE6: InstructionInfo{"set", "4, [ix+%ds8]", 1},
	0xE7: InstructionInfo{"set", "4, [ix+%ds8]->a", 1},
	0xE8: InstructionInfo{"set", "5, [ix+%ds8]->b", 1},
	0xE9: InstructionInfo{"set", "5, [ix+%ds8]->c", 1},
	0xEA: InstructionInfo{"set", "5, [ix+%ds8]->d", 1},
	0xEB: InstructionInfo{"set", "5, [ix+%ds8]->e", 1},
	0xEC: InstructionInfo{"set", "5, [ix+%ds8]->h", 1},
	0xED: InstructionInfo{"set", "5, [ix+%ds8]->l", 1},
	0xEE: InstructionInfo{"set", "5, [ix+%ds8]", 1},
	0xEF: InstructionInfo{"set", "5, [ix+%ds8]->a", 1},
	0xF0: InstructionInfo{"set", "6, [ix+%ds8]->b", 1},
	0xF1: InstructionInfo{"set", "6, [ix+%ds8]->c", 1},
	0xF2: InstructionInfo{"set", "6, [ix+%ds8]->d", 1},
	0xF3: InstructionInfo{"set", "6, [ix+%ds8]->e", 1},
	0xF4: InstructionInfo{"set", "6, [ix+%ds8]->h", 1},
	0xF5: InstructionInfo{"set", "6, [ix+%ds8]->l", 1},
	0xF6: InstructionInfo{"set", "6, [ix+%ds8]", 1},
	0xF7: InstructionInfo{"set", "6, [ix+%ds8]->a", 1},
	0xF8: InstructionInfo{"set", "7, [ix+%ds8]->b", 1},
	0xF9: InstructionInfo{"set", "7, [ix+%ds8]->c", 1},
	0xFA: InstructionInfo{"set", "7, [ix+%ds8]->d", 1},
	0xFB: InstructionInfo{"set", "7, [ix+%ds8]->e", 1},
	0xFC: InstructionInfo{"set", "7, [ix+%ds8]->h", 1},
	0xFD: InstructionInfo{"set", "7, [ix+%ds8]->l", 1},
	0xFE: InstructionInfo{"set", "7, [ix+%ds8]", 1},
	0xFF: InstructionInfo{"set", "7, [ix+%ds8]->a", 1},
}

var DisassemblyTable_FDCB = map[uint8]InstructionInfo{
	0x00: InstructionInfo{"rlc", "[iy+%ds8]->b", 1},
	0x01: InstructionInfo{"rlc", "[iy+%ds8]->c", 1},
	0x02: InstructionInfo{"rlc", "[iy+%ds8]->d", 1},
	0x03: InstructionInfo{"rlc", "[iy+%ds8]->e", 1},
	0x04: InstructionInfo{"rlc", "[iy+%ds8]->h", 1},
	0x05: InstructionInfo{"rlc", "[iy+%ds8]->l", 1},
	0x06: InstructionInfo{"rlc", "[iy+%ds8]", 1},
	0x07: InstructionInfo{"rlc", "[iy+%ds8]->a", 1},
	0x08: InstructionInfo{"rrc", "[iy+%ds8]->b", 1},
	0x09: InstructionInfo{"rrc", "[iy+%ds8]->c", 1},
	0x0A: InstructionInfo{"rrc", "[iy+%ds8]->d", 1},
	0x0B: InstructionInfo{"rrc", "[iy+%ds8]->e", 1},
	0x0C: InstructionInfo{"rrc", "[iy+%ds8]->h", 1},
	0x0D: InstructionInfo{"rrc", "[iy+%ds8]->l", 1},
	0x0E: InstructionInfo{"rrc", "[iy+%ds8]", 1},
	0x0F: InstructionInfo{"rrc", "[iy+%ds8]->a", 1},
	0x10: InstructionInfo{"rl", "[iy+%ds8]->b", 1},
	0x11: InstructionInfo{"rl", "[iy+%ds8]->c", 1},
	0x12: InstructionInfo{"rl", "[iy+%ds8]->d", 1},
	0x13: InstructionInfo{"rl", "[iy+%ds8]->e", 1},
	0x14: InstructionInfo{"rl", "[iy+%ds8]->h", 1},
	0x15: InstructionInfo{"rl", "[iy+%ds8]->l", 1},
	0x16: InstructionInfo{"rl", "[iy+%ds8]", 1},
	0x17: InstructionInfo{"rl", "[iy+%ds8]->a", 1},
	0x18: InstructionInfo{"rr", "[iy+%ds8]->b", 1},
	0x19: InstructionInfo{"rr", "[iy+%ds8]->c", 1},
	0x1A: InstructionInfo{"rr", "[iy+%ds8]->d", 1},
	0x1B: InstructionInfo{"rr", "[iy+%ds8]->e", 1},
	0x1C: InstructionInfo{"rr", "[iy+%ds8]->h", 1},
	0x1D: InstructionInfo{"rr", "[iy+%ds8]->l", 1},
	0x1E: InstructionInfo{"rr", "[iy+%ds8]", 1},
	0x1F: InstructionInfo{"rr", "[iy+%ds8]->a", 1},
	0x20: InstructionInfo{"sla", "[iy+%ds8]->b", 1},
	0x21: InstructionInfo{"sla", "[iy+%ds8]->c", 1},
	0x22: InstructionInfo{"sla", "[iy+%ds8]->d", 1},
	0x23: InstructionInfo{"sla", "[iy+%ds8]->e", 1},
	0x24: InstructionInfo{"sla", "[iy+%ds8]->h", 1},
	0x25: InstructionInfo{"sla", "[iy+%ds8]->l", 1},
	0x26: InstructionInfo{"sla", "[iy+%ds8]", 1},
	0x27: InstructionInfo{"sla", "[iy+%ds8]->a", 1},
	0x28: InstructionInfo{"sra", "[iy+%ds8]->b", 1},
	0x29: InstructionInfo{"sra", "[iy+%ds8]->c", 1},
	0x2A: InstructionInfo{"sra", "[iy+%ds8]->d", 1},
	0x2B: InstructionInfo{"sra", "[iy+%ds8]->e", 1},
	0x2C: InstructionInfo{"sra", "[iy+%ds8]->h", 1},
	0x2D: InstructionInfo{"sra", "[iy+%ds8]->l", 1},
	0x2E: InstructionInfo{"sra", "[iy+%ds8]", 1},
	0x2F: InstructionInfo{"sra", "[iy+%ds8]->a", 1},
	0x30: InstructionInfo{"sls", "[iy+%ds8]->b", 1},
	0x31: InstructionInfo{"sls", "[iy+%ds8]->c", 1},
	0x32: InstructionInfo{"sls", "[iy+%ds8]->d", 1},
	0x33: InstructionInfo{"sls", "[iy+%ds8]->e", 1},
	0x34: InstructionInfo{"sls", "[iy+%ds8]->h", 1},
	0x35: InstructionInfo{"sls", "[iy+%ds8]->l", 1},
	0x36: InstructionInfo{"sls", "[iy+%ds8]", 1},
	0x37: InstructionInfo{"sls", "[iy+%ds8]->a", 1},
	0x38: InstructionInfo{"srl", "[iy+%ds8]->b", 1},
	0x39: InstructionInfo{"srl", "[iy+%ds8]->c", 1},
	0x3A: InstructionInfo{"srl", "[iy+%ds8]->d", 1},
	0x3B: InstructionInfo{"srl", "[iy+%ds8]->e", 1},
	0x3C: InstructionInfo{"srl", "[iy+%ds8]->h", 1},
	0x3D: InstructionInfo{"srl", "[iy+%ds8]->l", 1},
	0x3E: InstructionInfo{"srl", "[iy+%ds8]", 1},
	0x3F: InstructionInfo{"srl", "[iy+%ds8]->a", 1},
	0x40: InstructionInfo{"bit", "0, [iy+%ds8]->b", 1},
	0x41: InstructionInfo{"bit", "0, [iy+%ds8]->c", 1},
	0x42: InstructionInfo{"bit", "0, [iy+%ds8]->d", 1},
	0x43: InstructionInfo{"bit", "0, [iy+%ds8]->e", 1},
	0x44: InstructionInfo{"bit", "0, [iy+%ds8]->h", 1},
	0x45: InstructionInfo{"bit", "0, [iy+%ds8]->l", 1},
	0x46: InstructionInfo{"bit", "0, [iy+%ds8]", 1},
	0x47: InstructionInfo{"bit", "0, [iy+%ds8]->a", 1},
	0x48: InstructionInfo{"bit", "1, [iy+%ds8]->b", 1},
	0x49: InstructionInfo{"bit", "1, [iy+%ds8]->c", 1},
	0x4A: InstructionInfo{"bit", "1, [iy+%ds8]->d", 1},
	0x4B: InstructionInfo{"bit", "1, [iy+%ds8]->e", 1},
	0x4C: InstructionInfo{"bit", "1, [iy+%ds8]->h", 1},
	0x4D: InstructionInfo{"bit", "1, [iy+%ds8]->l", 1},
	0x4E: InstructionInfo{"bit", "1, [iy+%ds8]", 1},
	0x4F: InstructionInfo{"bit", "1, [iy+%ds8]->a", 1},
	0x50: InstructionInfo{"bit", "2, [iy+%ds8]->b", 1},
	0x51: InstructionInfo{"bit", "2, [iy+%ds8]->c", 1},
	0x52: InstructionInfo{"bit", "2, [iy+%ds8]->d", 1},
	0x53: InstructionInfo{"bit", "2, [iy+%ds8]->e", 1},
	0x54: InstructionInfo{"bit", "2, [iy+%ds8]->h", 1},
	0x55: InstructionInfo{"bit", "2, [iy+%ds8]->l", 1},
	0x56: InstructionInfo{"bit", "2, [iy+%ds8]", 1},
	0x57: InstructionInfo{"bit", "2, [iy+%ds8]->a", 1},
	0x58: InstructionInfo{"bit", "3, [iy+%ds8]->b", 1},
	0x59: InstructionInfo{"bit", "3, [iy+%ds8]->c", 1},
	0x5A: InstructionInfo{"bit", "3, [iy+%ds8]->d", 1},
	0x5B: InstructionInfo{"bit", "3, [iy+%ds8]->e", 1},
	0x5C: InstructionInfo{"bit", "3, [iy+%ds8]->h", 1},
	0x5D: InstructionInfo{"bit", "3, [iy+%ds8]->l", 1},
	0x5E: InstructionInfo{"bit", "3, [iy+%ds8]", 1},
	0x5F: InstructionInfo{"bit", "3, [iy+%ds8]->a", 1},
	0x60: InstructionInfo{"bit", "4, [iy+%ds8]->b", 1},
	0x61: InstructionInfo{"bit", "4, [iy+%ds8]->c", 1},
	0x62: InstructionInfo{"bit", "4, [iy+%ds8]->d", 1},
	0x63: InstructionInfo{"bit", "4, [iy+%ds8]->e", 1},
	0x64: InstructionInfo{"bit", "4, [iy+%ds8]->h", 1},
	0x65: InstructionInfo{"bit", "4, [iy+%ds8]->l", 1},
	0x66: InstructionInfo{"bit", "4, [iy+%ds8]", 1},
	0x67: InstructionInfo{"bit", "4, [iy+%ds8]->a", 1},
	0x68: InstructionInfo{"bit", "5, [iy+%ds8]->b", 1},
	0x69: InstructionInfo{"bit", "5, [iy+%ds8]->c", 1},
	0x6A: InstructionInfo{"bit", "5, [iy+%ds8]->d", 1},
	0x6B: InstructionInfo{"bit", "5, [iy+%ds8]->e", 1},
	0x6C: InstructionInfo{"bit", "5, [iy+%ds8]->h", 1},
	0x6D: InstructionInfo{"bit", "5, [iy+%ds8]->l", 1},
	0x6E: InstructionInfo{"bit", "5, [iy+%ds8]", 1},
	0x6F: InstructionInfo{"bit", "5, [iy+%ds8]->a", 1},
	0x70: InstructionInfo{"bit", "6, [iy+%ds8]->b", 1},
	0x71: InstructionInfo{"bit", "6, [iy+%ds8]->c", 1},
	0x72: InstructionInfo{"bit", "6, [iy+%ds8]->d", 1},
	0x73: InstructionInfo{"bit", "6, [iy+%ds8]->e", 1},
	0x74: InstructionInfo{"bit", "6, [iy+%ds8]->h", 1},
	0x75: InstructionInfo{"bit", "6, [iy+%ds8]->l", 1},
	0x76: InstructionInfo{"bit", "6, [iy+%ds8]", 1},
	0x77: InstructionInfo{"bit", "6, [iy+%ds8]->a", 1},
	0x78: InstructionInfo{"bit", "7, [iy+%ds8]->b", 1},
	0x79: InstructionInfo{"bit", "7, [iy+%ds8]->c", 1},
	0x7A: InstructionInfo{"bit", "7, [iy+%ds8]->d", 1},
	0x7B: InstructionInfo{"bit", "7, [iy+%ds8]->e", 1},
	0x7C: InstructionInfo{"bit", "7, [iy+%ds8]->h", 1},
	0x7D: InstructionInfo{"bit", "7, [iy+%ds8]->l", 1},
	0x7E: InstructionInfo{"bit", "7, [iy+%ds8]", 1},
	0x7F: InstructionInfo{"bit", "7, [iy+%ds8]->a", 1},
	0x80: InstructionInfo{"res", "0, [iy+%ds8]->b", 1},
	0x81: InstructionInfo{"res", "0, [iy+%ds8]->c", 1},
	0x82: InstructionInfo{"res", "0, [iy+%ds8]->d", 1},
	0x83: InstructionInfo{"res", "0, [iy+%ds8]->e", 1},
	0x84: InstructionInfo{"res", "0, [iy+%ds8]->h", 1},
	0x85: InstructionInfo{"res", "0, [iy+%ds8]->l", 1},
	0x86: InstructionInfo{"res", "0, [iy+%ds8]", 1},
	0x87: InstructionInfo{"res", "0, [iy+%ds8]->a", 1},
	0x88: InstructionInfo{"res", "1, [iy+%ds8]->b", 1},
	0x89: InstructionInfo{"res", "1, [iy+%ds8]->c", 1},
	0x8A: InstructionInfo{"res", "1, [iy+%ds8]->d", 1},
	0x8B: InstructionInfo{"res", "1, [iy+%ds8]->e", 1},
	0x8C: InstructionInfo{"res", "1, [iy+%ds8]->h", 1},
	0x8D: InstructionInfo{"res", "1, [iy+%ds8]->l", 1},
	0x8E: InstructionInfo{"res", "1, [iy+%ds8]", 1},
	0x8F: InstructionInfo{"res", "1, [iy+%ds8]->a", 1},
	0x90: InstructionInfo{"res", "2, [iy+%ds8]->b", 1},
	0x91: InstructionInfo{"res", "2, [iy+%ds8]->c", 1},
	0x92: InstructionInfo{"res", "2, [iy+%ds8]->d", 1},
	0x93: InstructionInfo{"res", "2, [iy+%ds8]->e", 1},
	0x94: InstructionInfo{"res", "2, [iy+%ds8]->h", 1},
	0x95: InstructionInfo{"res", "2, [iy+%ds8]->l", 1},
	0x96: InstructionInfo{"res", "2, [iy+%ds8]", 1},
	0x97: InstructionInfo{"res", "2, [iy+%ds8]->a", 1},
	0x98: InstructionInfo{"res", "3, [iy+%ds8]->b", 1},
	0x99: InstructionInfo{"res", "3, [iy+%ds8]->c", 1},
	0x9A: InstructionInfo{"res", "3, [iy+%ds8]->d", 1},
	0x9B: InstructionInfo{"res", "3, [iy+%ds8]->e", 1},
	0x9C: InstructionInfo{"res", "3, [iy+%ds8]->h", 1},
	0x9D: InstructionInfo{"res", "3, [iy+%ds8]->l", 1},
	0x9E: InstructionInfo{"res", "3, [iy+%ds8]", 1},
	0x9F: InstructionInfo{"res", "3, [iy+%ds8]->a", 1},
	0xA0: InstructionInfo{"res", "4, [iy+%ds8]->b", 1},
	0xA1: InstructionInfo{"res", "4, [iy+%ds8]->c", 1},
	0xA2: InstructionInfo{"res", "4, [iy+%ds8]->d", 1},
	0xA3: InstructionInfo{"res", "4, [iy+%ds8]->e", 1},
	0xA4: InstructionInfo{"res", "4, [iy+%ds8]->h", 1},
	0xA5: InstructionInfo{"res", "4, [iy+%ds8]->l", 1},
	0xA6: InstructionInfo{"res", "4, [iy+%ds8]", 1},
	0xA7: InstructionInfo{"res", "4, [iy+%ds8]->a", 1},
	0xA8: InstructionInfo{"res", "5, [iy+%ds8]->b", 1},
	0xA9: InstructionInfo{"res", "5, [iy+%ds8]->c", 1},
	0xAA: InstructionInfo{"res", "5, [iy+%ds8]->d", 1},
	0xAB: InstructionInfo{"res", "5, [iy+%ds8]->e", 1},
	0xAC: InstructionInfo{"res", "5, [iy+%ds8]->h", 1},
	0xAD: InstructionInfo{"res", "5, [iy+%ds8]->l", 1},
	0xAE: InstructionInfo{"res", "5, [iy+%ds8]", 1},
	0xAF: InstructionInfo{"res", "5, [iy+%ds8]->a", 1},
	0xB0: InstructionInfo{"res", "6, [iy+%ds8]->b", 1},
	0xB1: InstructionInfo{"res", "6, [iy+%ds8]->c", 1},
	0xB2: InstructionInfo{"res", "6, [iy+%ds8]->d", 1},
	0xB3: InstructionInfo{"res", "6, [iy+%ds8]->e", 1},
	0xB4: InstructionInfo{"res", "6, [iy+%ds8]->h", 1},
	0xB5: InstructionInfo{"res", "6, [iy+%ds8]->l", 1},
	0xB6: InstructionInfo{"res", "6, [iy+%ds8]", 1},
	0xB7: InstructionInfo{"res", "6, [iy+%ds8]->a", 1},
	0xB8: InstructionInfo{"res", "7, [iy+%ds8]->b", 1},
	0xB9: InstructionInfo{"res", "7, [iy+%ds8]->c", 1},
	0xBA: InstructionInfo{"res", "7, [iy+%ds8]->d", 1},
	0xBB: InstructionInfo{"res", "7, [iy+%ds8]->e", 1},
	0xBC: InstructionInfo{"res", "7, [iy+%ds8]->h", 1},
	0xBD: InstructionInfo{"res", "7, [iy+%ds8]->l", 1},
	0xBE: InstructionInfo{"res", "7, [iy+%ds8]", 1},
	0xBF: InstructionInfo{"res", "7, [iy+%ds8]->a", 1},
	0xC0: InstructionInfo{"set", "0, [iy+%ds8]->b", 1},
	0xC1: InstructionInfo{"set", "0, [iy+%ds8]->c", 1},
	0xC2: InstructionInfo{"set", "0, [iy+%ds8]->d", 1},
	0xC3: InstructionInfo{"set", "0, [iy+%ds8]->e", 1},
	0xC4: InstructionInfo{"set", "0, [iy+%ds8]->h", 1},
	0xC5: InstructionInfo{"set", "0, [iy+%ds8]->l", 1},
	0xC6: InstructionInfo{"set", "0, [iy+%ds8]", 1},
	0xC7: InstructionInfo{"set", "0, [iy+%ds8]->a", 1},
	0xC8: InstructionInfo{"set", "1, [iy+%ds8]->b", 1},
	0xC9: InstructionInfo{"set", "1, [iy+%ds8]->c", 1},
	0xCA: InstructionInfo{"set", "1, [iy+%ds8]->d", 1},
	0xCB: InstructionInfo{"set", "1, [iy+%ds8]->e", 1},
	0xCC: InstructionInfo{"set", "1, [iy+%ds8]->h", 1},
	0xCD: InstructionInfo{"set", "1, [iy+%ds8]->l", 1},
	0xCE: InstructionInfo{"set", "1, [iy+%ds8]", 1},
	0xCF: InstructionInfo{"set", "1, [iy+%ds8]->a", 1},
	0xD0: InstructionInfo{"set", "2, [iy+%ds8]->b", 1},
	0xD1: InstructionInfo{"set", "2, [iy+%ds8]->c", 1},
	0xD2: InstructionInfo{"set", "2, [iy+%ds8]->d", 1},
	0xD3: InstructionInfo{"set", "2, [iy+%ds8]->e", 1},
	0xD4: InstructionInfo{"set", "2, [iy+%ds8]->h", 1},
	0xD5: InstructionInfo{"set", "2, [iy+%ds8]->l", 1},
	0xD6: InstructionInfo{"set", "2, [iy+%ds8]", 1},
	0xD7: InstructionInfo{"set", "2, [iy+%ds8]->a", 1},
	0xD8: InstructionInfo{"set", "3, [iy+%ds8]->b", 1},
	0xD9: InstructionInfo{"set", "3, [iy+%ds8]->c", 1},
	0xDA: InstructionInfo{"set", "3, [iy+%ds8]->d", 1},
	0xDB: InstructionInfo{"set", "3, [iy+%ds8]->e", 1},
	0xDC: InstructionInfo{"set", "3, [iy+%ds8]->h", 1},
	0xDD: InstructionInfo{"set", "3, [iy+%ds8]->l", 1},
	0xDE: InstructionInfo{"set", "3, [iy+%ds8]", 1},
	0xDF: InstructionInfo{"set", "3, [iy+%ds8]->a", 1},
	0xE0: InstructionInfo{"set", "4, [iy+%ds8]->b", 1},
	0xE1: InstructionInfo{"set", "4, [iy+%ds8]->c", 1},
	0xE2: InstructionInfo{"set", "4, [iy+%ds8]->d", 1},
	0xE3: InstructionInfo{"set", "4, [iy+%ds8]->e", 1},
	0xE4: InstructionInfo{"set", "4, [iy+%ds8]->h", 1},
	0xE5: InstructionInfo{"set", "4, [iy+%ds8]->l", 1},
	0xE6: InstructionInfo{"set", "4, [iy+%ds8]", 1},
	0xE7: InstructionInfo{"set", "4, [iy+%ds8]->a", 1},
	0xE8: InstructionInfo{"set", "5, [iy+%ds8]->b", 1},
	0xE9: InstructionInfo{"set", "5, [iy+%ds8]->c", 1},
	0xEA: InstructionInfo{"set", "5, [iy+%ds8]->d", 1},
	0xEB: InstructionInfo{"set", "5, [iy+%ds8]->e", 1},
	0xEC: InstructionInfo{"set", "5, [iy+%ds8]->h", 1},
	0xED: InstructionInfo{"set", "5, [iy+%ds8]->l", 1},
	0xEE: InstructionInfo{"set", "5, [iy+%ds8]", 1},
	0xEF: InstructionInfo{"set", "5, [iy+%ds8]->a", 1},
	0xF0: InstructionInfo{"set", "6, [iy+%ds8]->b", 1},
	0xF1: InstructionInfo{"set", "6, [iy+%ds8]->c", 1},
	0xF2: InstructionInfo{"set", "6, [iy+%ds8]->d", 1},
	0xF3: InstructionInfo{"set", "6, [iy+%ds8]->e", 1},
	0xF4: InstructionInfo{"set", "6, [iy+%ds8]->h", 1},
	0xF5: InstructionInfo{"set", "6, [iy+%ds8]->l", 1},
	0xF6: InstructionInfo{"set", "6, [iy+%ds8]", 1},
	0xF7: InstructionInfo{"set", "6, [iy+%ds8]->a", 1},
	0xF8: InstructionInfo{"set", "7, [iy+%ds8]->b", 1},
	0xF9: InstructionInfo{"set", "7, [iy+%ds8]->c", 1},
	0xFA: InstructionInfo{"set", "7, [iy+%ds8]->d", 1},
	0xFB: InstructionInfo{"set", "7, [iy+%ds8]->e", 1},
	0xFC: InstructionInfo{"set", "7, [iy+%ds8]->h", 1},
	0xFD: InstructionInfo{"set", "7, [iy+%ds8]->l", 1},
	0xFE: InstructionInfo{"set", "7, [iy+%ds8]", 1},
	0xFF: InstructionInfo{"set", "7, [iy+%ds8]->a", 1},
}