package cpu

type InstructionInfo struct {
	Mnemonic string
	Parameters string
	DataBytes uint8
}

var DisassemblyTable_Unprefixed = map[uint8]InstructionInfo {
	0x00: InstructionInfo{"nop", "", 0},
	0x01: InstructionInfo{"ld", "bc, %d16", 2},
	0x02: InstructionInfo{"ld", "(bc), a", 0},
	0x03: InstructionInfo{"inc", "bc", 0},
	0x04: InstructionInfo{"inc", "b", 0},
	0x05: InstructionInfo{"dec", "b", 0},
	0x06: InstructionInfo{"ld", "b, %d8", 1},
	0x07: InstructionInfo{"rlca", "", 0},
	0x08: InstructionInfo{"ex", "af, af'", 0},
	0x09: InstructionInfo{"add", "hl, bc", 0},
	0x0A: InstructionInfo{"ld", "a, (bc)", 0},
	0x0B: InstructionInfo{"dec", "bc", 0},
	0x0C: InstructionInfo{"inc", "c", 0},
	0x0D: InstructionInfo{"dec", "c", 0},
	0x0E: InstructionInfo{"ld", "c, %d8", 1},
	0x0F: InstructionInfo{"rrca", "", 0},
	0x10: InstructionInfo{"djnz", "%d16", 2},
	0x11: InstructionInfo{"ld", "de, %d16", 2},
	0x12: InstructionInfo{"ld", "(de), a", 0},
	0x13: InstructionInfo{"inc", "de", 0},
	0x14: InstructionInfo{"inc", "d", 0},
	0x15: InstructionInfo{"dec", "d", 0},
	0x16: InstructionInfo{"ld", "d, %d8", 1},
	0x17: InstructionInfo{"rla", "", 0},
	0x18: InstructionInfo{"jr", "%d16", 2},
	0x19: InstructionInfo{"add", "hl, de", 0},
	0x1A: InstructionInfo{"ld", "a, (de)", 0},
	0x1B: InstructionInfo{"dec", "de", 0},
	0x1C: InstructionInfo{"inc", "e", 0},
	0x1D: InstructionInfo{"dec", "e", 0},
	0x1E: InstructionInfo{"ld", "e, %d8", 1},
	0x1F: InstructionInfo{"rra", "", 0},
	0x20: InstructionInfo{"jr", "nz, %d16", 2},
	0x21: InstructionInfo{"ld", "hl, %d16", 2},
	0x22: InstructionInfo{"ld", "(%d16), h", 2},
	0x23: InstructionInfo{"inc", "hl", 0},
	0x24: InstructionInfo{"inc", "h", 0},
	0x25: InstructionInfo{"dec", "h", 0},
	0x26: InstructionInfo{"ld", "h, %d8", 1},
	0x27: InstructionInfo{"daa", "", 0},
	0x28: InstructionInfo{"jr", "z, %d16", 2},
	0x29: InstructionInfo{"add", "hl, hl", 0},
	0x2A: InstructionInfo{"ld", "hl, (%d16)", 2},
	0x2B: InstructionInfo{"dec", "hl", 0},
	0x2C: InstructionInfo{"inc", "l", 0},
	0x2D: InstructionInfo{"dec", "l", 0},
	0x2E: InstructionInfo{"ld", "l, %d8", 1},
	0x2F: InstructionInfo{"cpl", "", 0},
	0x30: InstructionInfo{"jr", "nc, %d16", 2},
	0x31: InstructionInfo{"ld", "sp, %d16", 2},
	0x32: InstructionInfo{"ld", "(%d16), a", 2},
	0x33: InstructionInfo{"inc", "sp", 0},
	0x34: InstructionInfo{"inc", "(hl)", 0},
	0x35: InstructionInfo{"dec", "(hl)", 0},
	0x36: InstructionInfo{"ld", "(hl), %d8", 1},
	0x37: InstructionInfo{"scf", "", 0},
	0x38: InstructionInfo{"jr", "c, %d16", 2},
	0x39: InstructionInfo{"add", "hl, sp", 0},
	0x3A: InstructionInfo{"ld", "a, (%d16)", 2},
	0x3B: InstructionInfo{"dec", "sp", 0},
	0x3C: InstructionInfo{"inc", "a", 0},
	0x3D: InstructionInfo{"dec", "a", 0},
	0x3E: InstructionInfo{"ld", "a, %d8", 1},
	0x3F: InstructionInfo{"ccf", "", 0},
	0x40: InstructionInfo{"ld", "b, b", 0},
	0x41: InstructionInfo{"ld", "b, c", 0},
	0x42: InstructionInfo{"ld", "b, d", 0},
	0x43: InstructionInfo{"ld", "b, e", 0},
	0x44: InstructionInfo{"ld", "b, h", 0},
	0x45: InstructionInfo{"ld", "b, l", 0},
	0x46: InstructionInfo{"ld", "b, (hl)", 0},
	0x47: InstructionInfo{"ld", "b, a", 0},
	0x48: InstructionInfo{"ld", "c, b", 0},
	0x49: InstructionInfo{"ld", "c, c", 0},
	0x4A: InstructionInfo{"ld", "c, d", 0},
	0x4B: InstructionInfo{"ld", "c, e", 0},
	0x4C: InstructionInfo{"ld", "c, h", 0},
	0x4D: InstructionInfo{"ld", "c, l", 0},
	0x4E: InstructionInfo{"ld", "c, (hl)", 0},
	0x4F: InstructionInfo{"ld", "c, a", 0},
	0x50: InstructionInfo{"ld", "d, b", 0},
	0x51: InstructionInfo{"ld", "d, c", 0},
	0x52: InstructionInfo{"ld", "d, d", 0},
	0x53: InstructionInfo{"ld", "d, e", 0},
	0x54: InstructionInfo{"ld", "d, h", 0},
	0x55: InstructionInfo{"ld", "d, l", 0},
	0x56: InstructionInfo{"ld", "d, (hl)", 0},
	0x57: InstructionInfo{"ld", "d, a", 0},
	0x58: InstructionInfo{"ld", "e, b", 0},
	0x59: InstructionInfo{"ld", "e, c", 0},
	0x5A: InstructionInfo{"ld", "e, d", 0},
	0x5B: InstructionInfo{"ld", "e, e", 0},
	0x5C: InstructionInfo{"ld", "e, h", 0},
	0x5D: InstructionInfo{"ld", "e, l", 0},
	0x5E: InstructionInfo{"ld", "e, (hl)", 0},
	0x5F: InstructionInfo{"ld", "e, a", 0},
	0x60: InstructionInfo{"ld", "h, b", 0},
	0x61: InstructionInfo{"ld", "h, c", 0},
	0x62: InstructionInfo{"ld", "h, d", 0},
	0x63: InstructionInfo{"ld", "h, e", 0},
	0x64: InstructionInfo{"ld", "h, h", 0},
	0x65: InstructionInfo{"ld", "h, l", 0},
	0x66: InstructionInfo{"ld", "h, (hl)", 0},
	0x67: InstructionInfo{"ld", "h, a", 0},
	0x68: InstructionInfo{"ld", "l, b", 0},
	0x69: InstructionInfo{"ld", "l, c", 0},
	0x6A: InstructionInfo{"ld", "l, d", 0},
	0x6B: InstructionInfo{"ld", "l, e", 0},
	0x6C: InstructionInfo{"ld", "l, h", 0},
	0x6D: InstructionInfo{"ld", "l, l", 0},
	0x6E: InstructionInfo{"ld", "l, (hl)", 0},
	0x6F: InstructionInfo{"ld", "l, a", 0},
	0x70: InstructionInfo{"ld", "(hl), b", 0},
	0x71: InstructionInfo{"ld", "(hl), c", 0},
	0x72: InstructionInfo{"ld", "(hl), d", 0},
	0x73: InstructionInfo{"ld", "(hl), e", 0},
	0x74: InstructionInfo{"ld", "(hl), h", 0},
	0x75: InstructionInfo{"ld", "(hl), l", 0},
	0x76: InstructionInfo{"halt", "", 0},
	0x77: InstructionInfo{"ld", "(hl), a", 0},
	0x78: InstructionInfo{"ld", "a, b", 0},
	0x79: InstructionInfo{"ld", "a, c", 0},
	0x7A: InstructionInfo{"ld", "a, d", 0},
	0x7B: InstructionInfo{"ld", "a, e", 0},
	0x7C: InstructionInfo{"ld", "a, h", 0},
	0x7D: InstructionInfo{"ld", "a, l", 0},
	0x7E: InstructionInfo{"ld", "a, (hl)", 0},
	0x7F: InstructionInfo{"ld", "a, a", 0},
	0x80: InstructionInfo{"add", "a, b", 0},
	0x81: InstructionInfo{"add", "a, c", 0},
	0x82: InstructionInfo{"add", "a, d", 0},
	0x83: InstructionInfo{"add", "a, e", 0},
	0x84: InstructionInfo{"add", "a, h", 0},
	0x85: InstructionInfo{"add", "a, l", 0},
	0x86: InstructionInfo{"add", "a, (hl)", 0},
	0x87: InstructionInfo{"add", "a, a", 0},
	0x88: InstructionInfo{"adc", "a, b", 0},
	0x89: InstructionInfo{"adc", "a, c", 0},
	0x8A: InstructionInfo{"adc", "a, d", 0},
	0x8B: InstructionInfo{"adc", "a, e", 0},
	0x8C: InstructionInfo{"adc", "a, h", 0},
	0x8D: InstructionInfo{"adc", "a, l", 0},
	0x8E: InstructionInfo{"adc", "a, (hl)", 0},
	0x8F: InstructionInfo{"adc", "a, a", 0},
	0x90: InstructionInfo{"sub", "a, b", 0},
	0x91: InstructionInfo{"sub", "a, c", 0},
	0x92: InstructionInfo{"sub", "a, d", 0},
	0x93: InstructionInfo{"sub", "a, e", 0},
	0x94: InstructionInfo{"sub", "a, h", 0},
	0x95: InstructionInfo{"sub", "a, l", 0},
	0x96: InstructionInfo{"sub", "a, (hl)", 0},
	0x97: InstructionInfo{"sub", "a, a", 0},
	0x98: InstructionInfo{"sbc", "a, b", 0},
	0x99: InstructionInfo{"sbc", "a, c", 0},
	0x9A: InstructionInfo{"sbc", "a, d", 0},
	0x9B: InstructionInfo{"sbc", "a, e", 0},
	0x9C: InstructionInfo{"sbc", "a, h", 0},
	0x9D: InstructionInfo{"sbc", "a, l", 0},
	0x9E: InstructionInfo{"sbc", "a, (hl)", 0},
	0x9F: InstructionInfo{"sbc", "a, a", 0},
	0xA0: InstructionInfo{"and", "b", 0},
	0xA1: InstructionInfo{"and", "c", 0},
	0xA2: InstructionInfo{"and", "d", 0},
	0xA3: InstructionInfo{"and", "e", 0},
	0xA4: InstructionInfo{"and", "h", 0},
	0xA5: InstructionInfo{"and", "l", 0},
	0xA6: InstructionInfo{"and", "(hl)", 0},
	0xA7: InstructionInfo{"and", "a", 0},
	0xA8: InstructionInfo{"xor", "b", 0},
	0xA9: InstructionInfo{"xor", "c", 0},
	0xAA: InstructionInfo{"xor", "d", 0},
	0xAB: InstructionInfo{"xor", "e", 0},
	0xAC: InstructionInfo{"xor", "h", 0},
	0xAD: InstructionInfo{"xor", "l", 0},
	0xAE: InstructionInfo{"xor", "(hl)", 0},
	0xAF: InstructionInfo{"xor", "a", 0},
	0xB0: InstructionInfo{"or", "b", 0},
	0xB1: InstructionInfo{"or", "c", 0},
	0xB2: InstructionInfo{"or", "d", 0},
	0xB3: InstructionInfo{"or", "e", 0},
	0xB4: InstructionInfo{"or", "h", 0},
	0xB5: InstructionInfo{"or", "l", 0},
	0xB6: InstructionInfo{"or", "(hl)", 0},
	0xB7: InstructionInfo{"or", "a", 0},
	0xB8: InstructionInfo{"cp", "b", 0},
	0xB9: InstructionInfo{"cp", "c", 0},
	0xBA: InstructionInfo{"cp", "d", 0},
	0xBB: InstructionInfo{"cp", "e", 0},
	0xBC: InstructionInfo{"cp", "h", 0},
	0xBD: InstructionInfo{"cp", "l", 0},
	0xBE: InstructionInfo{"cp", "(hl)", 0},
	0xBF: InstructionInfo{"cp", "a", 0},
	0xC0: InstructionInfo{"ret", "nz", 0},
	0xC1: InstructionInfo{"pop", "bc", 0},
	0xC2: InstructionInfo{"jp", "nz, %d16", 2},
	0xC3: InstructionInfo{"jp", "%d16", 2},
	0xC4: InstructionInfo{"call", "nz, %d16", 2},
	0xC5: InstructionInfo{"push", "bc", 0},
	0xC6: InstructionInfo{"add", "a, %d8", 1},
	0xC7: InstructionInfo{"rst", "%d8", 1},
	0xC8: InstructionInfo{"ret", "z", 0},
	0xC9: InstructionInfo{"ret", "", 0},
	0xCA: InstructionInfo{"jp", "z, %d16", 2},
	// CB prefix
	0xCC: InstructionInfo{"call", "z, %d16", 2},
	0xCD: InstructionInfo{"call", "%d16", 2},
	0xCE: InstructionInfo{"adc", "a, %d8", 1},
	0xCF: InstructionInfo{"rst", "0x08", 0},
	0xD0: InstructionInfo{"ret", "nc", 0},
	0xD1: InstructionInfo{"pop", "de", 0},
	0xD2: InstructionInfo{"jp", "nc, %d16", 2},
	0xD3: InstructionInfo{"out", "(%d8), a", 1},
	0xD4: InstructionInfo{"call", "nc, %d16", 2},
	0xD5: InstructionInfo{"push", "de", 0},
	0xD6: InstructionInfo{"sub", "a, %d8", 1},
	0xD7: InstructionInfo{"rst", "0x10", 0},
	0xD8: InstructionInfo{"ret", "c", 0},
	0xD9: InstructionInfo{"exx", "", 0},
	0xDA: InstructionInfo{"jp", "c, %d16", 2},
	0xDB: InstructionInfo{"i%d8", "a, (%d8)", 1},
	0xDC: InstructionInfo{"call", "c, %d16", 2},
	// DD prefix
	0xDE: InstructionInfo{"sbc", "a, %d8", 1},
	0xDF: InstructionInfo{"rst", "0x18", 0},
	0xE0: InstructionInfo{"ret", "po", 0},
	0xE1: InstructionInfo{"pop", "hl", 0},
	0xE2: InstructionInfo{"jp", "po, %d16", 2},
	0xE3: InstructionInfo{"ex", "(sp), hl", 0},
	0xE4: InstructionInfo{"call", "po, %d16", 2},
	0xE5: InstructionInfo{"push", "hl", 0},
	0xE6: InstructionInfo{"and", "%d8", 1},
	0xE7: InstructionInfo{"rst", "0x20", 0},
	0xE8: InstructionInfo{"ret", "pe", 0},
	0xE9: InstructionInfo{"jp", "hl", 0},
	0xEA: InstructionInfo{"jp", "pe, %d16", 2},
	0xEB: InstructionInfo{"ex", "de, hl", 0},
	0xEC: InstructionInfo{"call", "pe, %d16", 2},
	// ED prefix
	0xEE: InstructionInfo{"xor", "%d8", 1},
	0xEF: InstructionInfo{"rst", "0x28", 0},
	0xF0: InstructionInfo{"ret", "p", 0},
	0xF1: InstructionInfo{"pop", "af", 0},
	0xF2: InstructionInfo{"jp", "p, %d16", 2},
	0xF3: InstructionInfo{"di", "", 0},
	0xF4: InstructionInfo{"call", "p, %d16", 2},
	0xF5: InstructionInfo{"push", "af", 0},
	0xF6: InstructionInfo{"or", "%d8", 1},
	0xF7: InstructionInfo{"rst", "0x30", 0},
	0xF8: InstructionInfo{"ret", "m", 0},
	0xF9: InstructionInfo{"ld", "sp, hl", 0},
	0xFA: InstructionInfo{"jp", "m, %d16", 2},
	0xFB: InstructionInfo{"ei", "", 0},
	0xFC: InstructionInfo{"call", "m, %d16", 2},
	// FD prefix
	0xFE: InstructionInfo{"cp", "%d8", 1},
	0xFF: InstructionInfo{"rst", "0x38", 0},	
}